### ISSUE TITLE
add "not applicable" option for certain datasets for a country

### ISSUE THREAD

**Issue by LaurieJ** [okfn/opendatacensus#191]
Eg for Canada, there is apparently no meaningful national train or bus service so the question about transport cannot really be answered.  If there was a "not applicable" option, the results for canada would be more correct.

This would need to be incorporated in scoring, so the absence of open data for transport would not bring down Canada's overall score (ie scoring would disregard any datasets which are marked as "not applicable" when calculating the overall country score.)

**Comment by pwalsh** [comment]
@morchickit There is a lot of info here, and it is not relevant to code. 

I'm closing this issue, as it is really in your domain of methodology. 

If anything here needs further discussion, it should be taken up on the forum (or, @morchickit, you could copy some or all of this into a thread there): https://discuss.okfn.org/c/open-data-index

**Comment by morchickit** [comment]
Thanks Paul!
I'll take it up with @rgrp next week when we will finalise the methodology.
