### ISSUE TITLE
Functionality to sort country overview by each data category

### ISSUE THREAD

**Issue by autofunk** [okfn/opendatacensus#204]
Make it possible to sort country overview by each data category rather than only alphabetical or via total score.

**Comment by pwalsh** [comment]
@morchickit this seems quite esoteric, and it is almost 2 years old. I'm closing this issue, but if you want it, please capture it in a new user story.

**Comment by morchickit** [comment]
In any case, this is part of the Open Data Index repository and not the census, so no need to open it.
