### ISSUE TITLE
[discuss] Support for display year info (changes over time)

### ISSUE THREAD

**Issue by rgrp** [okfn/opendatacensus#304]
As per #281 we now only show most recent year data automatically (previously if we set display year to 2014 and there was 2013 data but no 2014 data the page was blank - now we'll show the 2013 data).

Proposal here is to introduce time (year) as an axis in display e.g.:

`/place/gb/2013` shows 2013 data only

**Comment by pwalsh** [comment]
This is now implemented: overview, dataset and place views now have year specific routes. eg:

/ <- current year overview
/2015 <- year overview
/places/{PLACE} <- current year overview
/places/{PLACE}/2015 <- year overview
/datasets/{DATASET} <- current year overview
/datasets/{DATASET}/2015 <- year overview
