### ISSUE TITLE
Add an "Submission Reviewed" attribute to each data set in the overview

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#319]
#### Description
Submissions have a few key questions asked of them, are they machine readable, publicly accessible, etc. We should add another question, has the entry been reviewed? This would add another grey box to the visualization until it has been reviewed.

The larger goal here is to ensure that every submission gets reviewed by a community member. We want to prevent the padding of scores and subpar submissions, while encouraging lots of eyes on the tool. The review of each dataset will give some more credibility to all of our work.

![screen shot 2014-04-10 at 5 40 41 pm](https://cloud.githubusercontent.com/assets/595778/2675217/1eb5c0ee-c112-11e3-87ca-ecbe22ad43ab.png) <- Add another box there
![screen shot 2014-05-03 at 11 34 51 am](https://cloud.githubusercontent.com/assets/595778/2871145/bb9a7738-d2f6-11e3-82fa-b253f8f9205c.png) <- Here as well

#### Files
templates/overview.html, lib/model.js

**Comment by pwalsh** [comment]
Closing. Most entries are reviewed, and those that are not, are not because it is a specific setting that allows this for particular census instances.
