### ISSUE TITLE
Dataset nesting by category in the future

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#322]
To add more datasets in the future and have the landing page of the Census still be legible, it might make sense to the nest the datasets by category:

e.g. a Property Data category that includes:
*  Code Enforcement Violations 
*  Property Assessment
*  Property Deeds ... etc 

Requested by @rebeccawilliams

**Comment by pwalsh** [comment]
@morchickit this is related to https://github.com/okfn/opendatacensus/issues/204 and the comments I made there.

1. Do we want to add something like this?
2. If yes, can it be captured in a new user story.

@ondrae I'm closing this issue as wontfix for now: Adding categories to datasets in the presentation layer would be a significant change I think, and if we are going to consider it, I'd like it to go through @morchickit and also be discussed with other census admins on the forum: https://discuss.okfn.org/c/open-data-index

**Comment by ondrae** [comment]
:+1:

**Comment by morchickit** [comment]
@ondrae I do not fully understand what you mean in this issue. Is this for the local census? Global? Is nesting really needed or is it depend on the datasets definitions? If you can elaborate more we can see where the discussion about this should go to. :-)

**Comment by pwalsh** [comment]
@morchickit ok - but discuss with @ondrae on forum pls until we have a clear course of technical action (or not) :)

**Comment by Stephen-Gates** [comment]
My thoughts - but I may be off on a tangent... 

Sometimes a census dataset, e.g. Government Facilities, is made up of multiple datasets. I ask contributors to list them all in the extra information question e.g. 
<img width="628" alt="screenshot 2015-07-22 06 39 27" src="https://cloud.githubusercontent.com/assets/9379524/8811928/9e244a68-303c-11e5-908f-1d1662ba6a76.png">
 
Each of these contributing datasets could be published differently and earn different census scores. Editors need some guidance on dealing with this situation if we aren't going to technically implement scoring for these "nested" datasets.
