### ISSUE TITLE
On US City Census, ask wether a user is a government employee

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#323]
#### Description
On sign in page, ask if they are a gov employee. If so, record their info and let gov-staff@codeforamerica.org know.  We want their name, their position, and their city.

Tell them we want their participation, but the census should be a community reviewed collection. We're trying to adapt this wonderful tool to be used by our [Brigade program](http://codeforamerica.org/brigade) in cities all across the country. We want community members to fill out and review the data, not government employees.

![screen shot 2014-04-24 at 2 24 43 pm](https://cloud.githubusercontent.com/assets/595778/2795212/09690030-cbf7-11e3-92f1-90c6df6a42c4.png) <- Ask on [this page](http://us-city.census.okfn.org/login)

**Comment by pwalsh** [comment]
Is this still relevant @ondrae ?

As I see it, this is not easy to implement, and would be easy to game. Do you have any suggestions?

**Comment by morchickit** [comment]
BTW - we have no easy way to authenticate someone is really a government employee. We have to mostly trust people to be honest.

**Comment by ondrae** [comment]
Its relevant, but not very practical.  We've just been going off of trust and will continue to do so. Sending gov employees away isnt very welcoming, when this may be some of their first open data community experience.
