### ISSUE TITLE
Missing contributors on City view

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#324]
We want to reflect the commitment of people who step up to be data librarians. They should be recognized on the [City view](http://us-city.census.okfn.org/place/sanfrancisco). Its missing right now.

![screen shot 2014-04-24 at 2 35 04 pm](https://cloud.githubusercontent.com/assets/595778/2795300/5e0f29e2-cbf8-11e3-866b-b3a829b55b38.png)

**Comment by pwalsh** [comment]
Exists in new codebase
