### ISSUE TITLE
Using a single, pre-populated google spreadsheet as `database` for testing considered harmful

### ISSUE THREAD

**Issue by andylolz** [okfn/opendatacensus#363]
* [x] Rather than have database fixtures in existing db (by hand) create all fixtures (and teardown) from code
   * Why? Using a pre-populated database spreadsheet means if a test times out or breaks, it can leave the spreadsheet in an unpredictable state. It takes one more test run to fix this.
* [x] Make test database configurable from config (though default to current if no entry in config)
  * Why? Allows people to more easily run the tests

Perhaps we could switch to using a blank database spreadsheet, and each user creates their own? This would also solve problems around sharing test user credentials.

**Comment by pwalsh** [comment]
We are removing dependency on spreadsheets as a database: https://github.com/okfn/opendatacensus/milestones/Database

wontfix.
