### ISSUE TITLE
submit/display pending changes at entry level on the Census

### ISSUE THREAD

**Issue by Feng-Gao** [okfn/opendatacensus#403]
Currently, only country page([UK](http://national.census.okfn.org/place/gb)) and dataset page([timetable](http://national.census.okfn.org/dataset/timetables)) shows pending changes and allows for submitting new changes. 

it seems to be also reasonable to list all pending changes on entry page (e.g. [UK timetable](http://national.census.okfn.org/entry/gb/timetables)) and allow new submission on the page as well. 

As for any newcomers to the Census/Index, it is reasonable to expect a link on the entry page to contribute new info. 

Is there a reason NOT to do this?

**Comment by morchickit** [comment]
I think this raise a whole new methodological issue - do we want to have multiple entries per dataset or are we accepting only one entry per dataset and allow people to comment on that entry. Having multiple entries per dataset was very confusing last year and didn't allow to have an easy comparative review between entries. I think we should go with the second option - have one entry per dataset and allow commenting on it. 
I will raise it on the discuss forum as well, but in the meanwhile @Feng-Gao , @pwalsh - what do you think?

**Comment by schlos** [comment]
+1 for Multiple entries per dataset

**Comment by pwalsh** [comment]
We are doing an overhaul of the design of these pages ( https://trello.com/c/uboCfkD3 ). I'm adding this for consideration, but closing this issue as it will be addressed through a new set of issues around the design of the census.
