### ISSUE TITLE
Create stable / production branch which has latest production code

### ISSUE THREAD

**Issue by rgrp** [okfn/opendatacensus#404]
* Create stable / production branch which has latest production code
* Tweak deploy and upgrade instructions to use this branch by default

Why: so we can deploy off stable code

Why not (?): master should be stable and if it is not let's patch it fast (new features can be done in branches)

**Comment by pwalsh** [comment]
FIXED. Default is now `develop` and stable will be `master`. Docs will be updated with the changes for database-refactor.
