### ISSUE TITLE
Add an option to show "add" and missing entries for dataset view

### ISSUE THREAD

**Issue by clkao** [okfn/opendatacensus#424]
for example, http://us-city.census.okfn.org/dataset/parcels can take a querystring param (or a global option) to show all cities, with "add" for the missing ones much like the overview page.

I think this makes it easy to send an url to a focus group to help out with census for particular topic.

**Comment by pwalsh** [comment]
I'm closing this. The new UX for the overview page takes care of the main user flow we want to support.
