### ISSUE TITLE
Share your submission to the Index

### ISSUE THREAD

**Issue by rgrp** [okfn/opendatacensus#463]
it would be useful to have a 'referral' twitter/fb ask built in for those who complete a census assessment.

If you fill in a survey, follow a 'write to your MP' or similar campaign things, you often get a pop-up that says 'thanks for helping - please tell your network on twitter or FB that you contributed so they can too' - something like that. With buttons for FB/Twitter which when you hit them gives you a ready-made tweet that could say 

'I've just #opendata in my region for #OpenIndex2014 - if you want to help build it check here http://bit.ly/1u1d2gk'

**Comment by pwalsh** [comment]
Was added last year.
