### ISSUE TITLE
Sanity check for the dependent field in question sheet

### ISSUE THREAD

**Issue by clkao** [okfn/opendatacensus#480]
This seems recently added.  If people are using a cloned or customized question sheet, odd things will happen.  There should be some warnings if basic sanity check does not pass.

**Comment by Stephen-Gates** [comment]
Sorry for potential cross posting - I just added the message below to Census Admin Google Group. I have tried using the provided URL to the question sheet and the questions imported into my own sheet but both give some result...

 **Dependency value missing for Uptodate row in Question sheet?**
Hi,
I can't get the survey to retain the value entered for the date the data was made available.

There is no value in the cell for dependency column and Uptodate row. When I guessed a value "date" the survey shows the the extra form element to capture the date the the information isn't retained when I review the submission.

What value should go in this cell?

The default Question sheet should be corrected, if I'm on the right track.

**Comment by pwalsh** [comment]
Hi @Stephen-Gates. The correct questions URL is here:

https://github.com/okfn/opendatacensus/issues/487

Let me know if that works for you.

If you have any problems that are related to the questions sheet, please continue in #487, not here.

Thanks.

**Comment by pwalsh** [comment]
I'm closing this issue. We've never supported or endorsed custom questions, and if people do use custom question, they should ensure they keep up-to-date with code changes. I'll add specific documentation to detail this as part of https://github.com/okfn/opendatacensus/issues/590
