### ISSUE TITLE
Update default question sheet with code rollout to city instances

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#487]
See #473 for background.

Required for correct support of the "title" > "officialtitle" change.

**Comment by pwalsh** [comment]
Started this:

* In shared city DB, renamed title > officialtitle in both submission and entry sheets
* Updated GB City config to use the new questions sheet (https://docs.google.com/spreadsheet/ccc?key=0AqR8dXc6Ji4JdE1QUS1qNjhvRDJaQy1TbTdJZDMtNFE#gid=3)
* Deployed latest code in `master` to UK

Additionally, 3 new instances deployed today also reference the new questions sheet:

* Caribbean Region
* Macedonia City
* Uruguay City

A 4th instance was deployed (Switzerland), but I can't edit the config file for it. @loleg I believe you are the admin for the Switzerland instance. Can you please add a questions key to your config with the above URL as the value, and then reload.

**Comment by pwalsh** [comment]
Also ar-city has been updated

**Comment by loleg** [comment]
Done, thanks kindly @pwalsh

**Comment by Stephen-Gates** [comment]
Thanks @pwalsh but that was the url I was provided. I just reloaded the site and no change. Try add a date for this dataset, http://australia.census.okfn.org/submit/?dataset=budget&place=test 

I can privately mail you the site config file url if required.

**Comment by pwalsh** [comment]
It works for me. What do you mean "add a date"? Can you please describe, exactly, what is not working?Sometimes it takes some minutes for changes to update. 

I don't need the site config, as I set it up :).

**Comment by Stephen-Gates** [comment]
@PWalsh, thanks for setting up the site.

To add a date value behind the informational calendar icon on http://australia.census.okfn.org/place/test, I assume I need to add it to the survey. When I select "yes" to the question, "Is the data provided on a timely and up to date basis?" The form does not expend to allow me to enter the date. 

I am using Safari (I noticed you had issues elsewhere with Safari)

![nodatepublished](https://cloud.githubusercontent.com/assets/9379524/6021559/6ba6534c-ac02-11e4-99b9-8ef5187370a0.png)

**Comment by Stephen-Gates** [comment]
When using the default question sheet, if you use {{questions}} in your site, you get [an extra row with a question mark in it](http://australia.census.okfn.org/faq/). I think the last blank row in the default question sheet needs to be deleted.

Further, the [description for scoring](http://index.okfn.org/methodology/) in the Global Open Data Index methodology, groups the questions as logical or technical. Feedback on my [FAQ page](http://australia.census.okfn.org/faq/#questions) said it would be good if the default questions followed that grouping.

Lastly, and please redirect me if this is in the wrong spot;  As it appears unwise to create my own question sheet, If I have suggestions for making the wording of the questions more concise how should this be proposed?

**Comment by Stephen-Gates** [comment]
In the question, "is the data machine readable", an invalid format is described as "JIF". I believe this should be "GIF".

**Comment by pwalsh** [comment]
Every single census instance is now running on the same code (master, latest commit).

@Stephen-Gates I'm moving your issues to their own issues (they are not directly related here): #502 #503 #504
