### ISSUE TITLE
Links in comments are created incorrectly

### ISSUE THREAD

**Issue by svanderwaal** [okfn/opendatacensus#489]
If there's a URL in the comments section of a submission, it gets displayed incorrectly on the dataset page. 

Example: http://global.census.okfn.org/entry/ro/elections 

The link looks like a valid link to http://alegeri.roaep.ro/, but the actual link address is "http://global.census.okfn.org/entry/ro/%3Ca%20href='http://alegeri.roaep.ro/'%20target='_blank'%3Ehttp://alegeri.roaep.ro/%3C/a%3E"

Source HTML is

`<a href="<a href='http://alegeri.roaep.ro/' target='_blank'>http://alegeri.roaep.ro/</a>">http://alegeri.roaep.ro/</a>`

**Comment by pwalsh** [comment]
fixed in database branch.
