### ISSUE TITLE
Add Australian City Census and other new ones to overview at http://census.okfn.org/local/

### ISSUE THREAD

**Issue by autofunk** [okfn/opendatacensus#492]
Overview at http://census.okfn.org/local/ is not complete. Add Australian City Census [http://au-city.census.okfn.org/] and other new ones from instance list: https://docs.google.com/a/okfn.org/spreadsheet/ccc?key=0AqR8dXc6Ji4JdHZoLXhLMjNVNjVPQzVlaU0tSjNUYlE#gid=0

**Comment by pwalsh** [comment]
FIXED.
