### ISSUE TITLE
Button Issue

### ISSUE THREAD

**Issue by badbruce07** [okfn/opendatacensus#494]
On the Caribbean Census website http://caribbean.census.okfn.org/ can the "Add contribution" button be changed to "Contribute data to the Census"?

---
addition by @pwalsh

* make the button text for the main "add information" button on the home page configurable
* make the display of the same button configurable (we disabled it on the global census; some city censuses make still want to use it though)

**Comment by pwalsh** [comment]
Hi @badbruce07. I'm answering your email here, as it is important that other team members can see bugs and enquiries from users of the census farm.

At some point, we changed the button from what it used to be to "Add information". It is not currently configurable on a per-census basis.

So, I'm updating the title of this issue to reflect the feature request, and adding some extra info to the description.

**Comment by Stephen-Gates** [comment]
When I was recently provided with [Australia's Regional Open Data Census](http://australia.census.okfn.org) my default site did not have a button.
I added the html below to the overview row in the configuration file and the button appeared and you can call it what you like.
```
 <p class="pull-right"> <a href="/submit/" class="btn btn-primary"> <i class="icon-plus"> </i> Submit an assessment </a> </p> 
```

**Comment by badbruce07** [comment]
oh ok cool @Stephen-Gates. One question, is the variable in the key column in the config file referred as "overview"?

**Comment by Stephen-Gates** [comment]
overview_page 

![contributebutton](https://cloud.githubusercontent.com/assets/9379524/6029039/8f25e044-ac39-11e4-85e9-9934c23e4717.png)

**Comment by pwalsh** [comment]
overview_page does add a text section to the home page (the "overview" page), but is is not the same section as the button that @badbruce07 is referring to. All the config options are here: http://census.okfn.org/doc/#general-config-options

**Comment by pwalsh** [comment]
Closing this as wontfix. Steps to solve the issue are noted above.
