### ISSUE TITLE
Fix Belgian City Census

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#495]
it broke from some bad data being added to config.

**Comment by pwalsh** [comment]
Hi @PieterJanPauwels

cc @autofunk 

The Belgian Census is working fine (I haven't touched it; just checked the config). I see the about page (wit the US content) here: http://be-city.census.okfn.org/about/

Perhaps there was just a temporary glitch?

I'm closing this issue but feel free to open if there are still problems.

**Comment by PieterJanPauwels** [comment]
Hi everyone, 

Maybe it was a glitch, but I had a downtime of +1 hour while being able to view the other Census pages with no issues. 
Very weird, but i’m glad it is online. Thank you for letting me know it is ok. 

Kind regards,
Pieter-Jan
	
Pieter-Jan Pauwels
Community Coordinator, Open Knowledge Belgium
m: +32 476 66 27 77 <tel:+32 476 66 27 77> | e: pieter-jan.pauwels@okfn.org <mailto:pieter-jan.pauwels@okfn.org> | w: okfn.be <http://okfn.be/>
