### ISSUE TITLE
Add extra documentation for census admins

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#496]
Describing all the steps required to configure a census instance in the farm. In particular, the extra steps required for the auth backend.

**Comment by pwalsh** [comment]
https://github.com/okfn/opendatacensus/commit/2ef2e5f9475f00145bbf1bfaa131af3786e5a4ca

**Comment by NotisPhil** [comment]
What is the "relevant folder" where the config spreadsheet has to be put in?

**Comment by pwalsh** [comment]
@NotisPhil that refers to the folder in the OK Drive account that holds the config files. This line could be removed from the docs.
