### ISSUE TITLE
Application error reloading Australian census

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#498]
I'm getting an application error when I reload this new census, http://australia.census.okfn.org/

` Application Error: An error occurred in the application and your page could not be served. Please try again in a few moments. If you are the application owner, check your logs for details. ` 

I thought it may be an error in the configuration sheet so I downloaded the current version and restored a prior known working version. Now I'm wondering if there's something else going on?

This issue was wrongly posted at https://github.com/okfn/opendataindex/issues/90 - Sorry.

**Comment by rgrp** [comment]
@pwalsh the us census is also down i think. I believe this is the usual "suspicious login" issue generating lock-out of google sheets. Can you take a look?

**Comment by pwalsh** [comment]
@rgrp yes I'll be looking at it shortly.

**Comment by pwalsh** [comment]
This is fixed. Was indeed the usual suspect: required a reset.

**Comment by Stephen-Gates** [comment]
Thanks @pwalsh much appreciated given impending launch

**Comment by pwalsh** [comment]
@Stephen-Gates no worries.
