### ISSUE TITLE
Add Australia's Regional Open Data Census

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#499]
I'm launching Australia's Regional Open Data Census on 21 Feb - Open Data Day. 
Please add australia.census.okfn.org to the list of censuses on census.okfn.org.
It would be great if this could be done before 19 Feb.

**Comment by pwalsh** [comment]
Done: http://census.okfn.org/local/

**Comment by Stephen-Gates** [comment]
Thanks @pwalsh - I like how you've split city and regional census. Perhaps a heading in-between would be nice so it appears as 2 alphabetical lists. Thanks again

**Comment by pwalsh** [comment]
Good idea, and I made that update. Thanks.
