### ISSUE TITLE
DE City seems to have a lot repetition of answers

### ISSUE THREAD

**Issue by rgrp** [okfn/opendatacensus#500]
See http://de-city.census.okfn.org/

**Comment by rgrp** [comment]
Note, someone from oklabs germany will likely be able to fix this!

**Comment by ondrae** [comment]
Same with the US City http://us-city.census.okfn.org/

**Comment by ondrae** [comment]
My first quick looks make it seem like It has to do something with the translations. Is there a setting we need to have that tells it which ones to include in the scoring?

**Comment by schlos** [comment]
Same problem is reproducible on http://hr-city.census.okfn.org

As CodeAcross is getting close, this seems like high priority. Can OKFN support us?

**Comment by pwalsh** [comment]
Hi,

Can anyone tell me when they first noticed this?

I'll be looking at it tomorrow.

**Comment by rgrp** [comment]
@pwalsh any chance to look at this today? This is obviously a significant issue. In terms of when it arose I saw it Thursday when I look at de-city census. I've already tried moving de-city codebase back to latest breaking change i.e. (going back further has issues because we've migrated the  data model). I note there is a chance some of this is to do with dependencies (e.g. a dependency version change getting pulled in). However, it does look like we are pinning most of our dependencies.

**Comment by pwalsh** [comment]
I haven't been available for work today, but I may have a few hours in the evening. I'll update here if I can. Otherwise, first thing tomorrow.

**Comment by pwalsh** [comment]
Hi all,

It was a copy/paste problem in the question sheet caused by me when doing a session with OK sys admins a few days ago. 

The questions were repeated ~ 22 times in the sheet.

The problem is now solved:

* http://de-city.census.okfn.org
* http://hr-city.census.okfn.org
* http://us-city.census.okfn.org

Please reopen if this problem re-appears.
