### ISSUE TITLE
Deleting a place?

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#501]
At present I have a place in the census for testing, http://australia.census.okfn.org/place/test 

Can I simply delete the entry in the google sheet for this place just before I go live without breaking anything?

**Comment by pwalsh** [comment]
Hi @Stephen-Gates you can safely remove the place from your spreadsheet.

**Comment by Stephen-Gates** [comment]
Thanks @pwalsh

**Comment by Stephen-Gates** [comment]
@pwalsh I've deleted the "test" place but the stats at the top of the page did not adjust. Is this something that gets fixed automatically in time or is this a bug?

**Comment by pwalsh** [comment]
Hi @Stephen-Gates ok, i see the issue. The entries also need to be removed from the submission and entry tables, which you do not have access to as the aus-region instance is running on a shared database with other instances.

I've removed those now, and things look fine. Please confirm.

**Comment by Stephen-Gates** [comment]
Perfect - All Fixed  :-)

Thanks heaps
