### ISSUE TITLE
Missing date field in submission form

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#504]
From @Stephen-Gates:

To add a date value behind the informational calendar icon on http://australia.census.okfn.org/place/test, I assume I need to add it to the survey. When I select "yes" to the question, "Is the data provided on a timely and up to date basis?" The form does not expand to allow me to enter the date.

I am using Safari (I noticed you had issues elsewhere with Safari).
Update: same behaviour in Chrome and Internet Explorer.

**Comment by pwalsh** [comment]
Hi @Stephen-Gates: 

This is a yes/no question - there is no entry for an actual date, only an indication that the dataset is timely.

**Comment by Stephen-Gates** [comment]
@pwalsh I'm not sure we're talking about the same thing. See how there is a data first made openly available date shown in the image below. Using the default questions, or my own variation, in http://australia.census.okfn.org, I can't get the date to store in the census and be displayed as shown below.

![screenshot 2015-02-16 06 05 50](https://cloud.githubusercontent.com/assets/9379524/6204758/37191570-b5a2-11e4-97c4-2f0d1fc5b61f.png)
