### ISSUE TITLE
Inconsistent pop-ups formatting

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#507]
The formatting of pop-ups is inconsistent (e.g. black/white background, headers).
When clicking a second icon to display a pop-up, the pop-up displayed from the first icon is not closed (unlike the auto-close behaviour on the global index (e.g. http://index.okfn.org/place/united-kingdom/)

![screenshot 2015-02-16 19 52 31](https://cloud.githubusercontent.com/assets/9379524/6210045/58d14c76-b617-11e4-9cd1-942f686513f0.png)

![screenshot 2015-02-16 06 05 50](https://cloud.githubusercontent.com/assets/9379524/6210114/216ae2e6-b618-11e4-9fbc-2825c6fbfd12.png)

Question pop-up text:
a) doesn't wrap for completed submissions.
b) text is centered for incompleted submissions.
Left justified, wrapped text would be desirable.

![screenshot 2015-02-16 19 59 29](https://cloud.githubusercontent.com/assets/9379524/6210111/1c33156e-b618-11e4-8146-043b351883bf.png)

![screenshot 2015-02-16 19 59 01](https://cloud.githubusercontent.com/assets/9379524/6210112/1c560696-b618-11e4-9436-298abc8ee14d.png)

**Comment by Stephen-Gates** [comment]
Problem appears to remain in place.next.census.okfn.org

**Comment by pwalsh** [comment]
Moved to #618
