### ISSUE TITLE
Editors and submitters not shown on Place/... page

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#511]
On http://australia.census.okfn.org/entry/qld/timetables editors and submitters **are shown**.
On http://australia.census.okfn.org/place/qld  editors and submitters **are not shown**.

I expected an aggregate of all editors and submitters to be shown on the place/... page. 

Is this the intended functionality? If so, it's not working.

**Comment by pwalsh** [comment]
Hi @Stephen-Gates no, there is no aggregate feature on the census site, even though I did add one for the global index site (e.g.: http://index.okfn.org/place/australia/)

It would be a nice addition here, but for the moment I'll add the request to the backlog.

**Comment by pwalsh** [comment]
fixed.
