### ISSUE TITLE
"Access for less secure apps" must be enabled in Administration Google Account

### ISSUE THREAD

**Issue by skorasaurus** [okfn/opendatacensus#512]
I wasn't able to get a local copy setup (using the code from master) until I authorized my gmail/google account to enable Access for less secure apps which can be configured by going to https://www.google.com/settings/security/lesssecureapps?pli=1

A quick mention of this in the documentation would be appreciated.  

Before I enabled access, I received the following error: 

```node run.js
Failed to login to primary database
Failed to load dataset info
Error: Login failed
    at null.<anonymous> (/my/pathto/opendatacensus/node_modules/google-spreadsheet/node_modules/googleclientlogin/index.js:146:15)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)```


Once I enabled access, I was able to run it locally.

**Comment by pwalsh** [comment]
WONTFIX. Not relevant once we launch the database refactor
