### ISSUE TITLE
README OAuth Instructions are Confusing

### ISSUE THREAD

**Issue by waldoj** [okfn/opendatacensus#513]
[The README](https://github.com/opendata/opendatacensus/blob/master/README.md#install-locally) says:

> For user Auth we use Google and their OAuth 2.0.
>
> you will need to create an App on Facebook developers section and set various config. See config section below for detail.

I have no idea of what this means. Facebook? For Google? "set various config"? I cannot find anything further about this in the config section.

As it stands now, clicking on the "Login with Google" button yields Google's Error 401 page:

> Error: invalid_client
> 
> The OAuth client was not found.
> 
> Request Details
> scope=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
response_type=code
redirect_uri=http://localhost:5000/auth/google/callback
client_id=unknown
>  That’s all we know.

There's nothing in [the docs](http://census.okfn.org/doc/) about OAuth, and no other relevant tickets that I can find.

Seems to me that the README needs instructions about how to support OAuth, so that it's possible to log in.

**Comment by pwalsh** [comment]
Hi,

The oauth docs are in the deploy section of the docs, which is for sys admin of census instances:

http://census.okfn.org/doc/deploy.html
