### ISSUE TITLE
Application Error loading http://australia.census.okfn.org/ #498 again?

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#515]
I'm getting an Application Error loading http://australia.census.okfn.org/ 
Tried reloading the site, same error occurs.
Is this #498 again?

**Comment by pwalsh** [comment]
Hey. Other instances are not down, so I think it may be a different issue. Have you made recent changes to the config file? In any event, I'll take a look shortly.

**Comment by Stephen-Gates** [comment]
Hi Paul, last change I recall is to FAQ row in general config tab - text about ODI certificates. This reloaded and was working.

**Comment by pwalsh** [comment]
Fixed. Was #498 again.
