### ISSUE TITLE
Multiple census not loading

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#517]
I'm getting an Application Error loading on a number of census sites. A persistent #498?

**Comment by pwalsh** [comment]
oh dear.... working on it.

**Comment by pwalsh** [comment]
Ok, we're back :)

**Comment by Stephen-Gates** [comment]
Thanks @pwalsh 
Is there a reason this keeps happening and a way to stop it?

**Comment by pwalsh** [comment]
There is a reason: we need to make some changes to stop it from happening. I'll try to prioritise this.
