### ISSUE TITLE
Update code for Node 0.12 (currently only supports 0.10.x)

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#518]
I discovered this the hard way now, while updating the server farm (CLI can't run under Node 0.12)

**Comment by skorasaurus** [comment]
Hi, 

Would you mind expanding what the issue was? 

I was trying to setup an instance locally on someone's computer last week and received a [build error](https://gist.github.com/skorasaurus/f7a9dad7103ec1d4d306). Not sure if it's a separate error or related to scrypt.

**Comment by pwalsh** [comment]
Hi @skorasaurus. I'd don't remember now and I didn't record the details, sorry.

**Comment by skorasaurus** [comment]
@pwalsh I think I found the culprit, making PR now.

**Comment by pwalsh** [comment]
awesome, thanks.

**Comment by pwalsh** [comment]
Done in feature/database-refactor
