### ISSUE TITLE
Application error - multiple census not loading (inc: USA, Australia and more)

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#519]
Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

**Comment by pwalsh** [comment]
Noted, will fix within 24 hours.

**Comment by JuryKonga** [comment]
Is it possible to get a monitoring service and an alert going to the DBA when this happens - especially when it hits every census.

**Comment by pwalsh** [comment]
@JuryKonga yes we'll look at doing that.

cc @rgrp @nigelbabu

**Comment by pwalsh** [comment]
Things are back to normal. Thanks for your patience.
