### ISSUE TITLE
Wanted to contribute but got this error:

### ISSUE THREAD

**Issue by natachaS** [okfn/opendatacensus#521]
I have followed all the instructions but still get this error when runnin node run.js

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Invalid closing quote at line 1; found "=" instead of delimiter ","
    at Parser.write (/Users/springern/Oss/opendatacensus/node_modules/csv/lib/parser.js:104:29)
    at CSV.write (/Users/springern/Oss/opendatacensus/node_modules/csv/lib/index.js:275:17)
    at Object._onImmediate (/Users/springern/Oss/opendatacensus/node_modules/csv/lib/from.js:175:11)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by pwalsh** [comment]
Hi. It appears that your config is not configured correctly.

Can you ensure that you are using the version of node in the package json, and then, provide a link to your config file so I can take a look?

**Comment by natachaS** [comment]
I am using v10 of Node and here' s the link to my config:
https://docs.google.com/spreadsheets/d/16D7Etwq2pkCQb74VfrS-ZvieAxBSPQxLRrtL5S-L7ZQ/edit#gid=0
Thanks for the help !

**Comment by pwalsh** [comment]
It looks like your config is "public on the web" but not "published to the web". The terminology is in the instructions, but admittedly this is an trick that we'll all been caught by in google docs.

The "publish to the web" functionality is in File > Publish to the Web

Does that help?

**Comment by pwalsh** [comment]
I'm closing this now.
