### ISSUE TITLE
Upload Croatian translation

### ISSUE THREAD

**Issue by schlos** [okfn/opendatacensus#522]
Could you support me and upload Croatian language on local census hr-city.census.okfn.org?

Language is already translated and reviewed on Transifex.

Or, share with me guide how can I add language on hr-city instance.

**Comment by schlos** [comment]
Transifex: https://www.transifex.com/projects/p/open-data-census/language/hr_HR/

**Comment by pwalsh** [comment]
Hi @schlos I should have some time to look at it later this week.

**Comment by pwalsh** [comment]
I haven't had time to look at census issues yet. It's on my list for this week. Feel free to bug me :).

**Comment by schlos** [comment]
Hi @pwalsh just checking in. Can I assist you in any way?

**Comment by pwalsh** [comment]
Hi @schlos . I'm terribly sorry for the lacking response. I'm working on some refactoring of the census code in order to fix some issues we've been having with uptime and the database. This process will likely take several weeks. In the meantime, I'm freezing work on the current censuses. Once we've got the new data backend in place and we can go live with it, I'll be able to help with this.

**Comment by schlos** [comment]
@pwalsh Hi! 
Any chance to upload Croatian translation to local city census instance (hr-city)?

**Comment by pwalsh** [comment]
Hi @schlos I'm trying to get to this, but other issues for the Global census take priority. When we start on fixes and enhancements for the local census instances, I'll ask @nealbastek to put this on high priority.

**Comment by pwalsh** [comment]
@kravets-levko can you have a look at this straight after the fixes for the API, but before you look at the tests. We might have to update some of the existing trans scripts (see README), possibly the language widget [here](https://github.com/okfn/opendatacensus/blob/develop/census/views/base.html#L98), and fix the fact that we have both a [`locale`](https://github.com/okfn/opendatacensus/tree/develop/census/locale) and [`locales`](https://github.com/okfn/opendatacensus/tree/develop/census/locales) directory (we should just have one). Ping me on slack for any help.

**Comment by pwalsh** [comment]
and...... it's live: http://hr-city.census.okfn.org/

thanks so much for your patience :).

**Comment by schlos** [comment]
:+1: 

Thank you @pwalsh and @kravets-levko
It will be much easier now to involve more people in evaluating cities!
