### ISSUE TITLE
Increment census year and compare results to previous year

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#523]
I'd like to document the process to end a census for a year and start the next year. Each census entry is provided with a census year but is closing the census as simple as changing the census year in the google sheet? 

I was advised by Christian Villum,
> Enabling year-to-year comparison is not currently available as far as I know, but you're not the first to ask. Would you mind filing a github issue with the question? Then Paul, our lead dev, can respond and outline what might be possible.

This functionality is very useful for publisher as it allows them to demonstrate progress over time. As we have had a number of changes in State Government recently, we are finding we have to re-educate new stakeholders and re-justify our efforts.

- Can the census year be incremented?
- What effect does that have (e.g. Census now is presented as empty)?
- Can results across year be compared?
- What are the plans moving forward (as I'll need to change the wording on Australia's Regional Open Data Census that assumed all this was possible)

Thanks in advance

**Comment by pwalsh** [comment]
New census now increments automatically per calendar year. Previous year data is available.
