### ISSUE TITLE
Application error on several pages

### ISSUE THREAD

**Issue by nyampire** [okfn/opendatacensus#526]
Application error occurs on some local census pages.
http://census.okfn.org/local/

**Comment by JuryKonga** [comment]
Hmmm - last time we had this, I suggested a monitoring tool so it could be recitifed quickly.  Its unfortunate that I've launched this initiative in Canada and I'm having people note the link doesn't work in a community forum :(    Is there a fundamental infrastructure problem here that needs to be addressed?

**Comment by pwalsh** [comment]
Hi. I've solved this issue now. We are working on a permanent solution to the problem, as announced here: https://lists.okfn.org/pipermail/open-data-census/2015-May/000659.html

**Comment by nyampire** [comment]
Thanks a lot!
