### ISSUE TITLE
Google deprecated the way this service access the spreadsheets on load

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#527]
I run an instance of the Open Data Census, with some customization of the front end features. The code is at https://github.com/codeforamerica/servicecensus and the site is usually live at https://service-census.herokuapp.com/

It is currently down due to now being able to login to the spreadsheet database when the app loads up. The same thing is happening to me locally.

```
Error: Login failed
    at null.<anonymous> (/Users/hackyourcity/Sites/servicecensus/node_modules/google-spreadsheet/node_modules/googleclientlogin/index.js:146:15)
```

The library used to login to the sheets (not oauth that individual users access) uses [a deprecated feature called ClientLogin](https://github.com/theoephraim/node-google-spreadsheet/issues/38#issuecomment-106547823).

I'm wondering how your network of sites is still up? I do notice that your login feature is turned off right now.  Do you have any advice for us running our own instances?

**Comment by pwalsh** [comment]
Hi @ondrae 

I made an announcement about this yesterday, here: 

https://discuss.okfn.org/t/all-census-instances-in-read-only-mode/339/5

The minimal fix I made to keep the census farm running is here:

https://github.com/pwalsh/opendatacensus/commits/hotfix/auth

And, I'm working on the refactor to a database backend now.

**Comment by pwalsh** [comment]
So, I'm closing this now. The path forward is:

* We'll be releasing a major update of the code in the next few weeks
* The largest change is that all data will be in a proper database
* Auth will be solved as part of the general refactor that removes reliance on the Spreadsheet API with authenticated requests, and updates to the way users work

Wrk is proceeding under the [Database Milestone](https://github.com/okfn/opendatacensus/milestones/Database)

**Comment by ondrae** [comment]
I've got the https://service-census.herokuapp.com/ working again.

I used a [Google Service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) to handle the auth. It involved upgrading a bunch of libraries in the census, and a ton of config changing. You can see at https://github.com/codeforamerica/servicecensus/commits/master

I can detail out what changes I made, perhaps even submit a PR, if you are interested in it.

If your work towards moving to Postgres is well underway though, then I wont distract you.

**Comment by pwalsh** [comment]
Hi @ondrae ok great. A PR would be really great for any other live custom forks of the census, but I'm not sure there are any except yours, and I won't merge it because of the size of the changes we are making now anyway. 

We had already planned and started the move to postgres anyway, as the current framework has been getting hard to manage with ~50 censuses we run.

I'll add a message about your fixes to the [thread on the forum](https://discuss.okfn.org/t/all-census-instances-in-read-only-mode/339).
