### ISSUE TITLE
No license on the code

### ISSUE THREAD

**Issue by svanderwaal** [okfn/opendatacensus#528]
There's no clear open source license on the codebase.

**Comment by pwalsh** [comment]
I'll take care of this. @rgrp MIT or AGPL?

**Comment by rgrp** [comment]
@pwalsh suggest AGPL.

**Comment by pwalsh** [comment]
Added in feature/database branch: https://github.com/pwalsh/opendatacensus/commit/dc2db706127f835c5300502132c2c37d931d0122

This will land in master in the coming 1-2 weeks.
