### ISSUE TITLE
Migrate all existing data

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#542]
* [x] `loaders._migrateDatabase` > `models.Entry`

this is just a one off flow for the db migration. Needs to be done for:

* [x] shared city db
* [x] us city db
* [x] global db
* [x] check if any other custom dbs

* [x] `loaders._migrateUsers` > `models.User`

**Comment by pwalsh** [comment]
## Notes on migrating Entries (copied from chat between @pwalsh and @gvidon)

* [Global Entry Database](https://docs.google.com/spreadsheets/d/1L49dmCBAQyc3hgiJCtLz0wqpbvecc-DGqTtiOq3NPEo/edit#gid=0)
* [Local Entry Database](https://docs.google.com/spreadsheets/d/1Qzd5TuzhauiK7OUS59UfZJJ759Un_rIPeIshjFkt3gA/edit#gid=0)

old data flow:

* user makes a submission
* submission goes to submission table
* reviewer reviews submission
* if reviewer approves a submission, the data is COPIED, including any changes the reviewer has made, which are not persisted in submission table, to the entry table

So, conceptually speaking, every object in the entry table has a matching object in submission table, but they may not in fact be "identical".

some expected data migration issues:

* Some of the timestamps are bad - maybe moment.js parser can handle, not sure.
* Resolving the "accepted" submission object for a given census,place,dataset,year with the entry object of the same. eg: `submission > entry` is now `entry.is_current = false > entry.is_current = true`

The logic for migrating, and resolving submissions/entries on old structure should look something like:

* IF submission.reviewresult == "accepted", and, 
* IF this submission has most recent timestamp of ALL "accepted" for this censusid,place,dataset,year, * THEN MERGE this submission with the object in entries sheet with matching censusid,place.dataset,year - there should only be one in entries that matches

Also note:

* Some things were strings and are now boolean (eg: `entry.reviewed`)
* New entry model has all answers to questions in a JSONB field: https://github.com/okfn/opendatacensus/blob/feature/database/census/models/entry.js#L37, instead of a more classic SQL pattern. I prefer this json blob considering the use case and the different answer types and so on - it simplfies things greatly in terms of modeling and querying
  * Note that most questions are simple yes/no questions: actually, "yes", "no" and "unsure". I think it might be useful to make these `true`, `false` and `null`. WDYT?

**Comment by gvidon** [comment]
## User migration CLI command
```sh
npm run loadusers <path to users .csv>
```

**Comment by gvidon** [comment]
@pwalsh how should new model fields ```submissionNotes``` and ```reviewComments```? What is the difference between ```Entry.submissionNotes``` and ```Entry.details```?

**Comment by pwalsh** [comment]
* `reviewComments` is a field on submission table. See [here](https://docs.google.com/spreadsheets/d/1L49dmCBAQyc3hgiJCtLz0wqpbvecc-DGqTtiOq3NPEo/edit#gid=0) on the global database.
* `Entry.submissionNotes` is submission.details, and `Entry.details` is entry.details

**Comment by gvidon** [comment]
@pwalsh what is ```Entry.answers``` for?

**Comment by pwalsh** [comment]
@gvidon as discussed via skype: Entry.answers holds answers to questions in a JSON object.

**Comment by gvidon** [comment]
Just to clarify

* IF submission.reviewresult == "accepted", and,
* IF this submission has most recent timestamp of ALL "accepted" for this censusid,place,dataset,year,
* THEN MERGE this submission with the object in entries sheet with matching censusid,place.dataset,year - there should only be one in entries that matches
* in new DB only Entry merged with submission which has most recent timestamp of ALL "accepted" for this censusid,place,dataset,year, has ```is_current === true```. ```is_current``` does not only mean ```reviewresult === "accepted"```

@pwalsh is last option correct?

**Comment by pwalsh** [comment]
@gvidon right now, Entry.reviewResult will be true, and is_current will be true, yes.
