### ISSUE TITLE
Setup changing of year as an instance wide config

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#544]
@rgrp @morchickit 

I see no reason why submission year needs to be entered by a census administrator as part of the config of a census. 

It has led to incorrect data in the past, because the administrator might not change this value (eg: 2013) even when people submit data in a different year (eg: 2014).

I propose that submission year be calculated by the app on startup, and it should be the current year that the application is running in. It's a job for the machine, not a human.

**Comment by rgrp** [comment]
Sounds sensible.

I think there was originally some though that year would not be calendar year but the "round" of the census that was happening (e.g. 2015 census might not begin until june). Right now, I'm not sure this is helpful and i think automating this would be useful.

**Comment by pwalsh** [comment]
done in https://github.com/okfn/opendatacensus/tree/feature/database

`app.get('year')`
