### ISSUE TITLE
No data in http://australia.next.census.okfn.org 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#556]
Australia's Regional Open Data Census went live in 2015.  It shows no data. The Download CSV file and Changes page return an application error.

**Comment by Stephen-Gates** [comment]
Similar issue with http://au-city.next.census.okfn.org

**Comment by pwalsh** [comment]
FIXED. Was missing some data from the old "Entries" table for local sites, probably due to a filter in Google Spreadsheets when I exported the data.
