### ISSUE TITLE
Rename "config" to "reload config" on place.next.census.okfn.org/admin/

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#558]
I was expecting to edit the config file here but got {"status":"ok","message":"ok"}. 
A nicer message would be good e.g. configuration file reloaded - goto place.next.census.okfn.org

It would be good to include links to the google sheet config files on this page.

**Comment by pwalsh** [comment]
Great idea! I will add links to the configured files.

**Comment by pwalsh** [comment]
@Stephen-Gates I've added a bunch of information to the site admin view. It is not pretty, but it works. This is all I can do for now, but please feel free to open a separate issue with specific improvements for the admin user experience, and we'll schedule them in.

**Comment by Stephen-Gates** [comment]
Well @pwalsh, that's a little bit awesome. :-)
