### ISSUE TITLE
Order of datasets has changed

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#559]
Not a big issue and assume can be corrected via config file but just interesting to note.Once http://australia.next.census.okfn.org has data I'll make sure it relates to the correct dataset.

**Comment by pwalsh** [comment]
Hmm. it is weird that "australia" doesn't have data (and some of the other issues). This might be specific to the renaming I did from "aus-region" > "australia" for the data on this census particularly. Checking out.

**Comment by pwalsh** [comment]
This is fixed. The order is now configurable for each census via the "order" property in the sheet. the value can be any valid integer from 0.

See the example here on the Australian census: https://docs.google.com/spreadsheets/d/1GOGRXgnYSAgl8rOEy4nkd8HfPDTWC8RHfv7fvKJddRA/edit#gid=2

http://australia.next.census.okfn.org/

To change order:

* Change the values in the sheet
* Reload the dataset configuration
