### ISSUE TITLE
Application error on http://australia.census.okfn.org 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#560]
Application error also occurs on a number of other census.

**Comment by pwalsh** [comment]
Hi @Stephen-Gates is there a reason you are using a custom question sheet? We strongly advise against it, and seeing as there are no translations required for Australia, I'm just wondering if I can change it to the standard question sheet: https://docs.google.com/spreadsheets/d/1nwmk8uJEK-4K6-5SdBgoLUlUos-BhfYRgjS74YkhDGc/edit#gid=3

**Comment by Stephen-Gates** [comment]
@pwalsh 
At the time, I believe the things that motivated me to change were:
 - I thought the wording of some questions was awkward.
 - I wanted to align the order of the questions with the [methodology scoring](http://index.okfn.org/methodology/) legal and technical groupings. 
 
Now, I am happy to use the standard questions because:
- the legal and technical groups [have been challenged](https://discuss.okfn.org/t/odd-technical-legal-categorizations-of-index-criteria/324) and I agree with the points made by @mlinksva and hope the methodology will be refined via @morchickit. 
- because it will make the conversion easier.

So,
- please use the standard questions for Australian census.
- I will propose the reworded questions as a change via the [forum](https://discuss.okfn.org/c/open-data-index)
- And, If I really can't live with it, perhaps "Australian" deserves to be recognised as an official language and I translate the questions - bonza beauty bottler mate, 'nother prawn on the barbie? ;-)

**Comment by pwalsh** [comment]
Hi @Stephen-Gates 

Thanks for the explanation. I will change to the standard question sheet, but please, do follow up these issues with @morchickit and if we need to change this back to a custom sheet, we can do that. I can also add support for Australian if we really need it :).

**Comment by pwalsh** [comment]
Hi Stephen. Now I see that with this issue, you meant the existing code, and now the new code. I'm porting over the "next" over to the main domains in the next 24 hours, and there will be some downtime during this while old DNS records are removed and new ones resolve. So, instead of fixing this old site, we'll just wait for the actual move.
