### ISSUE TITLE
Submissions broken for US City project

### ISSUE THREAD

**Issue by oxguy3** [okfn/opendatacensus#561]
I tried to submit information for Construction Permits for Philadelphia PA in the US City project. When I submitted, there was an alert saying my submission had been successfully received, but there was also a 404 error. Now, when I try to access [the page for Philadelphia](http://us-city.next.census.okfn.org/place/philly/2015), I get this error:

    500: Internal Server Error
    
    Something is up with the server.
    Template render error: Error: Unable to call `reviewer["fullName"]`, which is undefined or falsey

**Comment by pwalsh** [comment]
Hi @oxguy3 yes. As stated in the announcement, submissions are not working yet:

https://discuss.okfn.org/t/all-census-instances-in-read-only-mode/339/16

**Comment by pwalsh** [comment]
I'll leave this open though until that works as well.

**Comment by oxguy3** [comment]
Ah sorry, I missed that note; mea culpa.

**Comment by pwalsh** [comment]
@oxguy3 no, it is fine.

**Comment by pwalsh** [comment]
This is fixed now. If you find this not to be the case @oxguy3 please let me know, and open a specific ticket with the details.
