### ISSUE TITLE
Dataset name missing in {{datasets}}

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#562]
Using {{datasets}} in http://australia.next.census.okfn.org/faq/#questions the dataset name is missing
<img width="998" alt="screenshot 2015-07-20 06 21 32" src="https://cloud.githubusercontent.com/assets/9379524/8767701/7e15a2b6-2ea8-11e5-8327-9e3b89baaff5.png">

**Comment by pwalsh** [comment]
fixed.
