### ISSUE TITLE
Obvious way to return to current year

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#563]
After exploring earlier years (i.e. 2013 | 2014) there is no obvious way to return to 2015. I know you can go to the home page but I wonder if adding arrows or an extra label would help.
e.g.  <- 2014 ->   or   2013 | **2014** | 2015

<img width="640" alt="screenshot 2015-07-20 06 34 46" src="https://cloud.githubusercontent.com/assets/9379524/8767754/1e28776e-2eaa-11e5-8820-2d7dc6d6bb39.png">

**Comment by pwalsh** [comment]
Ok. The "other years" section needs a bit of design work done too.

**Comment by pwalsh** [comment]
I've added this to the year navigation.
