### ISSUE TITLE
Compare results by year in regional and local open data census

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#564]
The Global Open Data Index (GODI) provides the ability to compare results between years. This sort of comparison is important to engage stakeholders in discussions regarding the need to improve. Consider adding the ability to demonstrate progress over time. This could include the ability to:
- download data by year so users can create their own charts
- showing the change from the last period (see screen shots from GODI below)

<img width="1174" alt="screenshot 2015-07-20 06 54 06" src="https://cloud.githubusercontent.com/assets/9379524/8774237/4a69e8ce-2f1f-11e5-91d8-11a4e67a7ae4.png">

<img width="610" alt="screenshot 2015-07-20 06 54 45" src="https://cloud.githubusercontent.com/assets/9379524/8774238/4abc6982-2f1f-11e5-9efd-7ddb342c333a.png">

**Comment by pwalsh** [comment]
@morchickit @rgrp could also be useful in relation to https://github.com/okfn/opendatacensus/issues/620 and https://github.com/okfn/opendatacensus/issues/619?

**Comment by morchickit** [comment]
No, it's a different on for the meanwhile.
I'll flag it to Neal as the local index product owner. 
WONTFIX for now

**Comment by pwalsh** [comment]
@nealbastek for you consideration.

**Comment by pwalsh** [comment]
The work this year will mean that the "Index" codebase can be used by all instances of the census.

This is captured in these user stories:

- https://trello.com/c/3tQEO31y
- https://trello.com/c/PM7LjKm6

The specific details of how comparison from "old" methodologies to the new one(s) going forward is not define yet, and likely not to happen. Discussion for that belongs here: https://discuss.okfn.org/t/introducing-the-new-proposed-global-open-data-index-survey/3104
