### ISSUE TITLE
Excessive anonymous contributors and anonymous editors

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#565]
Rollup anonymous contributors to avoid pages that look like this...
(not quite sure how we have anonymous editors)

<img width="967" alt="screenshot 2015-07-20 20 59 35" src="https://cloud.githubusercontent.com/assets/9379524/8774510/6485354e-2f22-11e5-8a57-a2c469e0a303.png">

**Comment by pwalsh** [comment]
Fixed.
