### ISSUE TITLE
Formating and missing data on place/dataset/year pages

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#566]
Few issues on these pages:
- missing Data Location value (but available on dataset/year page)
- timely data text wrapping is awkward 
- excessive anonymous submitters (see #565) 
- still has tool tip issue (similar to #507)

<img width="963" alt="screenshot 2015-07-20 21 19 40" src="https://cloud.githubusercontent.com/assets/9379524/8774773/149c9cae-2f25-11e5-9a0c-e307e8882fe5.png">

**Comment by pwalsh** [comment]
Fixed data location and anonymous submitters. Other issues are annoying but not critical. Adding to backlog.

**Comment by pwalsh** [comment]
Moved to #618
