### ISSUE TITLE
Submitter shown as Editor/Reviewer

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#567]
Mark Cottman-Fields is not an editor/reviewer for Australia's Regional Open Data Census. 
This submission has been made but not reviewed by editors.

Same issue occurs on:
- http://australia.next.census.okfn.org/entry/qld/crime-stats/2015 (uses term reviewer)
- http://australia.next.census.okfn.org/place/qld/2015 (uses term editor - not sure how this differs from reviewer)

<img width="828" alt="screenshot 2015-07-20 22 41 13" src="https://cloud.githubusercontent.com/assets/9379524/8775948/78cbd716-2f30-11e5-8c45-950f1dfbe940.png">

<img width="818" alt="screenshot 2015-07-20 22 31 44" src="https://cloud.githubusercontent.com/assets/9379524/8775840/67fcfeb6-2f2f-11e5-9af8-93ea4fbd9c52.png">

**Comment by pwalsh** [comment]
When a submission is made, and no entry exists, it automatically becomes an entry, and therefore, the submitter becomes the reviewer. If we put aside for a moment whether that is right or wrong behaviour, does that explain what you see here?

**Comment by Stephen-Gates** [comment]
Yes, Mark's submission was the first.

**Comment by pwalsh** [comment]
Ok. @morchickit @Stephen-Gates  what do you think about this?

The current code sets the submitter as the reviewer, when the submitter's submission gets automatically set as the "current entry". 

I see no particular problem with this. I can probably change it if we must.

**Comment by Stephen-Gates** [comment]
@pwalsh the behaviour is explainable but in my view not ideal. I'd prefer to put it on the backlog and focus on getting the census back online.

**Comment by pwalsh** [comment]
Ok, I'm leaving it as is (unless @morchickit has further comments). Any future changes then will not be retroactive, if we do change the behaviour in the future.

**Comment by morchickit** [comment]
So, in theory - this should not be a problem for the Global Index, but I can see how it can be a problem for the local index. Let's put it on the local backlog? 
@Stephen-Gates - you are doing an amazing job, keep flagging if you think we should change something in any time, we will review it later.

**Comment by pwalsh** [comment]
This is now on backlog. Current behaviour remains.

**Comment by pwalsh** [comment]
Ok: behaviour going forward is going to be: submissions that are accepted without review (ie: due to the "approve_first_submission" setting), will not have a reviewer, which is in line with what @Stephen-Gates has requested above. Old data (anything before today), will have the submitter as the reviewer, as noted above.

So, I'm closing this issue now. If we **really** need to act on this for old data, we should have a new ticket explaining the specific issue, but I don't think it is likely to get high priority.
