### ISSUE TITLE
Problem report and review for Next city census instance

### ISSUE THREAD

**Issue by schlos** [okfn/opendatacensus#570]
- [x] after submitting, it will be displayed to user "NAME, You do not have permissions to review this submission." it's rather confusing, why it's displayed to submitter right after submission? IMHO, it would be logical to display "Your submission is waiting for review before it is published." - [screenshot](https://qsnapnet.com/snaps/vsbqfnfvp4gta9k)

- [x] changes listed on "Changes" screen are not reachable (Error 404), example: [Changes](http://hr-city.next.census.okfn.org/changes/) > [404: Not Found](http://hr-city.next.census.okfn.org/submission/76ed38fe-2ec4-4ddb-91aa-b8e565c3b18a) - [screenshot](https://qsnapnet.com/snaps/bjdhccaf13e4s4i)

- [x] description text (in yellow box) does not support Markdown syntax anymore? [example page](http://hr-city.next.census.okfn.org/census/submit/?dataset=building-permits&place=ka) - [screenshot](https://qsnapnet.com/snaps/hpr1ydq5ipugzao)

- [x] dataset screen has offset in table header: URL is in year column, Information is in URL column. [example page](http://hr-city.next.census.okfn.org/dataset/zoning/2015) - [screenshot](https://qsnapnet.com/snaps/5krokapmloldte2)

- [x] dataset and place screen, header table is missing label for "Year" column. [place screen](http://hr-city.next.census.okfn.org/place/ka/2015) - [place screenshot](https://qsnapnet.com/snaps/58qhypz2x8g833d) | [dataset screen](http://hr-city.next.census.okfn.org/dataset/zoning/2015) - [dataset screenshot](https://qsnapnet.com/snaps/4z450qoe71a714i)

- [x] propose revision, then switch to other city other dataset - same information is retained (is this as per design?). i.e. 1st open [dataset screen](http://hr-city.next.census.okfn.org/dataset/zoning/2015), 2nd step click on propose revision button for [GIS Zoning, place Karlovac](http://hr-city.next.census.okfn.org/census/submit/?dataset=zoning&place=ka), in 3rd step user decided to try different dataset, and even different screen, use dropdowns to change dataset and place ([screenshot](https://qsnapnet.com/snaps/p8caxqnzpnb9ms4)), in 4th step user changed dataset (i.e. Budget) and place (i.e. Zagreb) which does not have yet any inputed data, now check submission form. Result: form is already prefilled with old GIS Zoning for place Karlovac. Expected: changing place and dataset should not be possible on "Propose revision" screen.

- [x] Download Data (CSV) link in footer is not working (timeout occurs), [example link](http://hr-city.next.census.okfn.org/api/entries.csv)

**Comment by pwalsh** [comment]
@schlos thanks. for the "propose revision" point (your 6th), I see the problem, but that is how the design has always been. When I fix these other issues tomorrow, I'll probably pull that one out as a separate task for the backlog, as it requires some more thought on how to resolve this.

**Comment by pwalsh** [comment]
@schlos for the first point: it does display a message as you describe, as well as the "can't review" message if the user who submitted cannot review. Both these messages serve a purpose, so I'm not changing that for now.

**Comment by pwalsh** [comment]
All fixed except CSV. That has its own issue now: https://github.com/okfn/opendatacensus/issues/575

**Comment by schlos** [comment]
@pwalsh 

point 2:
I can still reproduce. I've opened new ticket for that: #606
"changes listed on "Changes" screen are not reachable (Error 404)"

point 3:
MD will be re-added or we're moving to html syntax?
"description text (in yellow box) does not support Markdown syntax anymore?"

point 4:
I can still reproduce it: http://hr-city.census.okfn.org/dataset/zoning/2014
"dataset screen has offset in table header: URL is in year column, Information is in URL column."

point 5:
ok, fixed
"dataset screen has offset in table header: URL is in year column, Information is in URL column."
