### ISSUE TITLE
When submitting, I have to re-choose the place and dataset

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#571]
I've navigated to a place and chosen a dataset. When I tried to make a submission, I have to rechoose the place and the dataset. The data is right there in the url though.

![screen shot 2015-07-21 at 10 49 36 am](https://cloud.githubusercontent.com/assets/595778/8808238/4506d582-2f96-11e5-92ce-4edcd05c9efa.png)

**Comment by pwalsh** [comment]
@ondrae very good thanks. it is a simple bug. will fix tomorrow.

**Comment by pwalsh** [comment]
fixed.
