### ISSUE TITLE
Proposed change to Entry not shown as Pending in /Changes

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#572]
Did this change http://australia.next.census.okfn.org/census/submission/9cd618f9-444d-4916-b469-bd92aae0000b but on going to http://australia.next.census.okfn.org/changes/ didn't see the change as pending and sometimes got a blank page.

**Comment by Stephen-Gates** [comment]
Note: got to page to make change via + Add Information on Home Page (i.e. not via Propose Revisions)

**Comment by Stephen-Gates** [comment]
Same result when going via Propose Revisions http://australia.next.census.okfn.org/census/submission/7e01ea53-6afb-4bb4-91bf-406f0b96a419

**Comment by pwalsh** [comment]
Hi @Stephen-Gates 

It is there, it is just that the ordering is wrong. I've sorting the ordering now and redeployed.

<img width="1280" alt="screenshot 2015-07-22 09 13 27" src="https://cloud.githubusercontent.com/assets/791678/8819136/f4c3746a-3051-11e5-87ce-49c7e3eb9762.png">
