### ISSUE TITLE
Approved revision only partially updates

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#573]
I approved a change and the results where reflected at: 
- http://australia.next.census.okfn.org/entry/qld/election 
- http://australia.next.census.okfn.org/dataset/election/2015

but not at: 
- http://australia.next.census.okfn.org/

**Comment by pwalsh** [comment]
@Stephen-Gates it looks like it has updated to me. What signs should I look for here?

**Comment by Stephen-Gates** [comment]
I changed the dataset to not available and this is reflected on 
- http://australia.next.census.okfn.org/entry/qld/election
- http://australia.next.census.okfn.org/dataset/election/2015

but on the home page is not all red as in the links above.
![qldbudget](https://cloud.githubusercontent.com/assets/9379524/8819732/1f419dda-3092-11e5-86d6-5ff02ad8daf2.PNG)

**Comment by pwalsh** [comment]
it is QLD Election.

**Comment by Stephen-Gates** [comment]
Do'h 
Closing Now - Sorry

**Comment by pwalsh** [comment]
no worries!
