### ISSUE TITLE
First entry does not need review but UI displays as review needed

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#574]
http://australia.next.census.okfn.org/place/nt/2015 shows Awaiting review...

![ntfirstentry](https://cloud.githubusercontent.com/assets/9379524/8819553/9a8a3bca-3090-11e5-8cf3-d1923aa05226.PNG)

On attempting to review, there is no option to approve/reject. Is that because another submission was approved after it or will all first entries be like that?

![nt2](https://cloud.githubusercontent.com/assets/9379524/8819586/e91e27c4-3090-11e5-9bea-646c6335b05d.PNG)

Will test further.

**Comment by Stephen-Gates** [comment]
Ok added http://australia.next.census.okfn.org/census/submission/13c11600-0eef-4b2e-a759-a1b9593cf609 and got Publish/Reject buttons but as a first entry it didn't appear on:

- http://australia.next.census.okfn.org/
- http://australia.next.census.okfn.org/dataset/budget/2015 

but appears on 
- http://australia.next.census.okfn.org/place/nsw/2015 as awaiting review but it is the first entry and should auto-publish.

**Comment by pwalsh** [comment]
Ok, this is a bug with approve first review, and then related side effects. Working on it now.

**Comment by pwalsh** [comment]
@morchickit the behaviour of "approve first submission" will change slightly: previously, it meant the first submission ever for a given census/place/dataset. Now that the census handles data by year properly, I think the correct behaviour would be "approve first submission for the given census/place/dataset this YEAR".

@Stephen-Gates if you have any thoughts on this, would love to hear them

**Comment by Stephen-Gates** [comment]
@pwalsh auto-approval each year sound good.

**Comment by morchickit** [comment]
@pwalsh - I am a bit confused - approved means approved by reviewer OR is it ready go to review?

**Comment by pwalsh** [comment]
@morchickit there is a setting that census admins can use to have a submission automatically "accepted" (bypassing the review process). So, we are talking about that setting.

**Comment by morchickit** [comment]
OK, I remember that setting. Then the new change sound fine.

**Comment by pwalsh** [comment]
@Stephen-Gates this is fixed now: the first submission setting is now respected per "site" (eg: australia, global), and is year-sensitive.
