### ISSUE TITLE
Fix Download Data links

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#575]
The code was recently refactored. The links to download entry data as CSV and JSON were not fixed as part of the refactor. (These links can be found in the footer).

We currently have [this controller that allows download as JSON](https://github.com/okfn/opendatacensus/blob/develop/census/controllers/pages.js#L69) (and works), and also [this module](https://github.com/okfn/opendatacensus/blob/develop/census/controllers/api.js) which is a non-working API

* [x] Expose API views via the api module, where the user can download data as CSV or JSON
* [x] The data to be downloaded is "Entries", that is, objects in the `Entry` table where `isCurrent` is `true`
* [x] Allow the following queries, **per site** (see how all the current code is site-specific, as the app hosts multiple tenants - one per site):
  * [x] Get all current entries for all years
  * [x] Get all current entries for a given year (from the available years in the DB)
* [x] For the JSON views, the objects can be output pretty much as they are stored (answers in a nested object)
* [x] For the CSV views, we need to flatten answers
  * [This is the old database](https://docs.google.com/spreadsheets/d/1Fg4rhor38z4hkQzLw1LwNCq03RSgPxP1ykUrEvvuEQs/edit#gid=1) - the CSV output should look something like this - ie - answers object flattened into CSV row

**Comment by rgrp** [comment]
I would say this is very secondary right now ;-) (we def want to do it but it could wait).

**Comment by stevage** [comment]
Ever so slightly ironic filling in a survey that judges organisations on whether or not they allow bulk download of their data when... :)

I actually want to use the data from au-city.census.okfn.org to make a map. Basically, a census version of http://map.opencouncildata.org/

**Comment by pwalsh** [comment]
@stevage ok. we are scheduled to do it this week, as you can see it is assigned. On the other hand, this an open source project and we are happy to get PRs.

**Comment by stevage** [comment]
Whoops, sorry for unintended snark.

**Comment by pwalsh** [comment]
@stevage no worries.

**Comment by kravets-levko** [comment]
PR https://github.com/okfn/opendatacensus/pull/694

**Comment by pwalsh** [comment]
FIXED.
