### ISSUE TITLE
Unable to add Pathway entry for Noosa on Australia's Local Open Data Census 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#577]
I have tried multiple times to add a submission for this data http://www.data.gov.au/dataset/noosa-pathways on http://au-city.census.okfn.org/place/noosa_shire_council/2015

I am logged in but get different results if I choose to submit as a named or anonymous user but in both cases can't add the submission

<img width="1000" alt="screenshot 2015-07-22 21 56 27" src="https://cloud.githubusercontent.com/assets/9379524/8824834/ed23b2ae-30bc-11e5-9255-802a29c74a87.png">

**Comment by pwalsh** [comment]
Hi @Stephen-Gates 

I need some more information here. 

I can see that:

1. You have made other successful submissions on the au-city site (eg: http://au-city.census.okfn.org/census/submission/b4f62ead-44cc-4274-8e93-2b9ff8a3ac5c)
2. A large amount of data has been added to the au-city site in the last few hours (eg: place count has doubled)

**Comment by Stephen-Gates** [comment]
Many Queensland councils have been added as new Places. I have tried to a submission for a new place, Noosa.

The submission you reference above is for Brisbane which already existed as a place.

Does that help?

**Comment by pwalsh** [comment]
Was not related to new data. Was a bug. fixed in https://github.com/okfn/opendatacensus/commit/e5f4471a1a56ba760e1663ce6c681669425facf9

**Comment by Stephen-Gates** [comment]
Success http://au-city.census.okfn.org/census/submission/516c620b-4140-448b-8327-001a3a23d900 

Thanks @pwalsh

**Comment by maxious** [comment]
I'm getting generic application errors accepting this submission. Tried a couple of different comments.

**Comment by Stephen-Gates** [comment]
...and as the first submission for a Place + Dataset + Year it should have been automatically made an entry unless @maxious you've configured the site not to allow this  (see #574)

**Comment by pwalsh** [comment]
@maxious ok will check it out.

**Comment by Stephen-Gates** [comment]
Successfully submitted NSW Budget for first time but not automatically added as entry http://australia.census.okfn.org/census/submission/9e7f1f10-8e90-45b6-bb72-1372be5b24b1 

Will check configuration in Sheet

**Comment by pwalsh** [comment]
@Stephen-Gates yes, `approve_first_submission` is `FALSE` if it does not exist.

**Comment by pwalsh** [comment]
@maxious fixed silly bug that caused the behaviour you experienced.
