### ISSUE TITLE
Order of {{Datasets}} does not match dataset order on census home page

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#579]
Not a big issue but the dataset order is different between http://australia.census.okfn.org/faq/#datasets with http://australia.census.okfn.org

<img width="341" alt="screenshot 2015-07-22 23 37 18" src="https://cloud.githubusercontent.com/assets/9379524/8826552/a009266c-30ca-11e5-8996-5e070fdb78ec.png"> 

<img width="1005" alt="screenshot 2015-07-22 23 36 02" src="https://cloud.githubusercontent.com/assets/9379524/8826525/799ccd58-30ca-11e5-870f-ed854c497db8.png">

**Comment by pwalsh** [comment]
FIXED (also question sorting).
