### ISSUE TITLE
If a dataset has characteristics, implement logic on how this relates to submission questions

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#584]
Requires same spec as https://github.com/okfn/opendatacensus/issues/587

**Comment by pwalsh** [comment]
From @morchickit 

<img src="https://docs.google.com/drawings/d/1jj0mnDjvzz-O8SNBgEhNTqsXa8SNdMoMeoxPoy-tBfE/pub?w=1060&amp;h=738">

**Comment by rgrp** [comment]
This is deferred for now. I would suggest we close as WONTFIX for now and re-open or open a new question when needed. /cc @pwalsh @morchickit

**Comment by pwalsh** [comment]
WONTFIX
