### ISSUE TITLE
Have a normalized list of machine readable formats, and tie the machine readable + format questions

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#585]
@morchickit I need a definitive list of formats we consider machine readable, including their extensions/identifiers in all variations.

A comprehensive list of non-machine readable formats would also be good.

**Comment by Stephen-Gates** [comment]
I went looking for a list this and found a dead page off the Open Definition and updated it to tackle this (and other problems) http://opendefinition.org/ofd/ 

I need to update it when [v2.1](https://github.com/okfn/opendefinition/blob/master/source/open-definition-2.1-dev.markdown) of the Open Definition is released and narrow it down to a list of formats. 

I was struggling with section 1.2 and 1.3 in the [Open Definition](http://opendefinition.org/od/) but the "fuzziness" as been removed. 

I proposed approving formats as being compliant with the Open Definition ([as per licences](http://opendefinition.org/licenses/)) but that idea was not supported. ([Discussion started here](https://lists.okfn.org/pipermail/od-discuss/2015-April/001330.html).)

Hope this helps. Let me know if I can help further.

@pwalsh This feature will need to support adding multiple formats for one dataset - I did a CSV, GeoJSON, WMS, WFS entry last night.

**Comment by morchickit** [comment]
SO - @Stephen-Gates , I am not sold on aligning the census with Open formats (yet). I think that if a government is releasing data in XLS instead of a CSV it should be penalised for it. It is hard for us to explain to the what machine readable is, that I feel it will be unfair to be neat peaking about it (I can convert a XLS to CSV easily, and it works on 99% (if not all) other software out there. 
First see that governments publish in machine readable formats, then lets scale it to better formats.

**Comment by Stephen-Gates** [comment]
OK @morchickit - You gotta start somewhere. We can crank things up over time.

**Comment by morchickit** [comment]
Yes - I am not against the idea, I just don't think we are there (yet!). It will be great to see if we can do it in years to come.

**Comment by morchickit** [comment]
OK - After analysing last's year submissions, I came up with this list. @Stephen-Gates , @rgrp - Tell me if I missed something!

Not Machine readable
PDF
HTML
XHTML
WORD


Machine readable 
CSV
CIF
RDF
JSON
XLS
TXT
TEXTO (the Spanish way to say text file - it was mentioned more than one in 2014!)
GTFS (Technically, its a standard that creates text files, but if someone writes this we should mark the data as machine readable)
Geo JSON
WMS
Shapefile
WFS

**Comment by Stephen-Gates** [comment]
KML

**Comment by pwalsh** [comment]
@morchickit there is no longer a user story for this issue, nor any clear technical action to take.

Therefore, I suggest we start a discussion in the forum to build lists of machine readable formats (and/or non-machine readable) with the wider community, and from there decide if there is action to take now or in near future for local census work, by farming it in a user story and prioritizing it.

So, I'm closing this issue here.
