### ISSUE TITLE
As a site admin, I want to be able to generate some reports on census activity

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#586]
@morchickit need a reasonable, minimal list of useful reports. 

Expected behaviour is that user will get a CSV file that has data for such a report, and the admin can use Excel or whatever to work with this CSV.

**Comment by Stephen-Gates** [comment]
As a data publisher, progress over time is always handy. See an example at http://australia.census.okfn.org/faq/#data

**Comment by pwalsh** [comment]
The user story has been changed. Will be covered by a new issue.
