### ISSUE TITLE
Implement updated dependencies between questions based on updated methodology

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#587]
Requires spec for @morchickit

**Comment by pwalsh** [comment]
From @morchickit 

<img src="https://docs.google.com/drawings/d/1jj0mnDjvzz-O8SNBgEhNTqsXa8SNdMoMeoxPoy-tBfE/pub?w=1060&amp;h=738">

**Comment by rgrp** [comment]
@morchickit i should catch up with you on this diagram as not sure all the implications work (e.g. data vailable online = No !=> openly licensed no or bulk = no)

**Comment by morchickit** [comment]
It's and not or, and we can do whenever you want, the sooner the better.

**Comment by rgrp** [comment]
This is now finalized.

**Comment by pwalsh** [comment]
Actual work being done here: https://github.com/okfn/opendatacensus/issues/610
