### ISSUE TITLE
Google name not showing correctly on review submission page 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#588]
Logged in with Australia's Open Data Index account but name not defined in text, "As the reviewer, your name (undefined) will be logged and displayed with the entry".

<img width="1004" alt="screenshot 2015-07-23 06 57 50" src="https://cloud.githubusercontent.com/assets/9379524/8837183/64bc9fc4-3108-11e5-944d-3fe75cdfb055.png">

**Comment by pwalsh** [comment]
fixed.

**Comment by Stephen-Gates** [comment]
Not convinced Earl's last name is really "null".  @pwalsh Probably related to above.

http://australia.census.okfn.org/changes/

<img width="633" alt="screenshot 2015-07-23 20 14 12" src="https://cloud.githubusercontent.com/assets/9379524/8848051/b466911e-3177-11e5-92cf-3d343facbed7.png">

**Comment by pwalsh** [comment]
Fixed. Also fixed another bug that prevented user's last names from being saved in database with they log in.
