### ISSUE TITLE
Text overlaps on Submission review page 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#592]
On http://australia.census.okfn.org/census/submission/1cdf9bf7-f148-48df-b4f8-614df96a0777 
parts of the page are not attractive...
<img width="967" alt="screenshot 2015-07-23 21 45 41" src="https://cloud.githubusercontent.com/assets/9379524/8849619/73ef67fc-3184-11e5-8744-33fdc5b65831.png">

**Comment by Stephen-Gates** [comment]
... and a missing space after "Submitter: "
<img width="395" alt="screenshot 2015-07-23 21 49 33" src="https://cloud.githubusercontent.com/assets/9379524/8849661/d1825758-3184-11e5-8930-7075e744848c.png">

**Comment by pwalsh** [comment]
The missing space is fixed. the other issue is annoying, but only appears on particularly long texts for this text field. Will add to backlog for now.

**Comment by pwalsh** [comment]
Moved to #618
