### ISSUE TITLE
Links on Login page broken

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#593]
These should return to the Place.census pages or be removed.

<img width="789" alt="screenshot 2015-07-23 21 58 25" src="https://cloud.githubusercontent.com/assets/9379524/8849823/1bec6c60-3186-11e5-9599-c26c429a7d10.png">

<img width="618" alt="screenshot 2015-07-23 21 58 35" src="https://cloud.githubusercontent.com/assets/9379524/8849828/201e9be6-3186-11e5-9a8b-0ba61600c721.png">

**Comment by pwalsh** [comment]
Yes this one I know about. We'll deal with it and related here https://github.com/okfn/opendatacensus/issues/568
