### ISSUE TITLE
Two revisions added for same dataset with editor review in-between 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#594]
As originally discussed on #591 on http://australia.census.okfn.org/place/qld/2015 I have a dataset, government facilities, with multiple submissions awaiting review. These two entries were added by the same person half an hour apart. 
<img width="964" alt="screenshot 2015-07-23 21 39 16" src="https://cloud.githubusercontent.com/assets/9379524/8854436/3a35dea0-31a3-11e5-9474-69b96283592a.png">

How should this be addressed? Reject both and ask for resubmission (as I know the submitter)?

**Comment by pwalsh** [comment]
The fact that there are two was due to a bug that has now been fixed. Also, for reference, data that was migrated from the old spreadsheets to the new DB may also have more than one pending submission.

My suggestion is to reject duplicates or stale submissions. Form this point onwards, the system only allows one pending submission.

**Comment by Stephen-Gates** [comment]
Rejected both entries. Not reflected in change log. Still appear in http://australia.census.okfn.org/place/qld/2015

**Comment by pwalsh** [comment]
@Stephen-Gates 

I fixed the bug related to rejecting entries. Please confirm. I'll close the issue when you confirm.

**Comment by Stephen-Gates** [comment]
@pwalsh strange behaviors... actions don't appear to be accurately reflected in /changes

I attempted to keep the original and reject the latest from Earl but that got rid of the original.

I'm confused to what's going on here - maybe something related to submission sequence?

**Comment by pwalsh** [comment]
i see the problem. I'm working on it now

**Comment by pwalsh** [comment]
Please check again.

**Comment by Stephen-Gates** [comment]
I have taken no action in census:
- Change log shows correctly. Original Accepted and one of Earl's Rejected.
- http://australia.census.okfn.org/place/qld/2015 shows Earl's other submission is Pending awaiting review 
-  However the comments are from the original are missing. Actually just noticed comments are missing in the whole census (raise as separate issue?)

So now I'll attempt to reject...

**Comment by pwalsh** [comment]
separate issues for everything, yes. but, please expand on what you mean by "comments"

**Comment by Stephen-Gates** [comment]
Rejected pending submission:
- Change log correct
- http://australia.census.okfn.org correct
- http://australia.census.okfn.org/place/qld/2015 correct
- http://australia.census.okfn.org/entry/qld/facilities/2015 correct  but not processing markdown in comments (will add separate issue)
<img width="954" alt="screenshot 2015-07-26 20 11 40" src="https://cloud.githubusercontent.com/assets/9379524/8893413/b0aeb044-33d2-11e5-9650-b6f7186e5459.png">
