### ISSUE TITLE
Remove "+add Information button from home page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#595]
![screen shot 2015-07-23 at 16 31 04](https://cloud.githubusercontent.com/assets/3273659/8854595/8c08625c-3158-11e5-9d45-3851ca177e9c.png)

**Comment by Stephen-Gates** [comment]
@morchickit what's the thinking here?

**Comment by morchickit** [comment]
This button create lots of confusion when users are filling the census during the global index. Having one point of entry of data should make it easier for them to know what to do.

**Comment by Stephen-Gates** [comment]
Are you removing 
<img width="163" alt="screenshot 2015-07-24 21 11 44" src="https://cloud.githubusercontent.com/assets/9379524/8873319/b40608ea-3248-11e5-9e64-6b6359843e6b.png"> 

or the multiple +Add buttons in the grid display? 
<img width="190" alt="screenshot 2015-07-24 21 13 37" src="https://cloud.githubusercontent.com/assets/9379524/8873340/e9dbef52-3248-11e5-98af-3af09130f35a.png">

100% agree with removing all the +Add buttons. I always found it confusing.
<img width="58" alt="screenshot 2015-07-24 21 11 36" src="https://cloud.githubusercontent.com/assets/9379524/8873356/1a91d9c2-3249-11e5-8cb2-ea1821fa2b8f.png">

**Comment by morchickit** [comment]
I was thinking if removing the first option (the big blue button). @Stephen-Gates  - you think we should remove the one per countries? Thats a b good option as well... @pwalsh  - what will be easier?

**Comment by pwalsh** [comment]
You need the +Add per country as a call to action to drill down and then add from a specific point (eg: qld/contracts).

The problem last year was that the blue +Add lead to multiple queued submissions, which is not possible now anyway.

Abut easier - doesn't matter. What gives the best ux? I think the best ux is that people "Add" from a place or dataset page, as there they have the context of current pending submissions for example.

We still need an action on the overview page to get there - so, even if we should maybe change the wording, I think the best ux is the inlined +add buttons.

**Comment by Stephen-Gates** [comment]
My logic is:
- pressing **+Add information** takes you to /submit where you can do what the button says. 
- pressing **+Add** takes you to /place - not what I was expecting, where I need to press "add" again.

Could pressing **+Add** in the grid take you to /submit with Place and Dataset pre-filled? That's what I was expecting to happen.

**Comment by pwalsh** [comment]
@Stephen-Gates yes, it could (should). please add it as a new issue.

**Comment by pwalsh** [comment]
Changes in #619 will cover this
