### ISSUE TITLE
Cannot review existing submission

### ISSUE THREAD

**Issue by schlos** [okfn/opendatacensus#596]
I can access admin page:
http://hr-city.census.okfn.org/admin/

But cannot review existing submission:
http://hr-city.census.okfn.org/changes/

"Miroslav, You do not have permissions to review this submission."

**Comment by pwalsh** [comment]
The email address you are logged in with must be an email in the reviewers field of the config.

It looks like yours is, but email addresses in your config were space separated, comma separated. The old code allowed space separated, so it is a bug that the new code does not.

https://docs.google.com/spreadsheets/d/1FCAnp_sksyb2FREVjw-qpDbJEVo5efRqiQP1OT1krDM/edit#gid=0

I updated your config now to have commas. Please "Reload config" from the /admin page, and try again.

**Comment by schlos** [comment]
Ok, tnx. I'm now recognized as a reviewer.
