### ISSUE TITLE
How to define reviewers in new admin page?

### ISSUE THREAD

**Issue by schlos** [okfn/opendatacensus#597]
How to define reviewers in new admin page?

Cant seem to find anything to "edit", just links to old spreadsheets (we dont use spreadsheets anymore, right?) and relead data (from where?).

**Comment by pwalsh** [comment]
As previously, all config changes are done in a google spreadsheet: http://census.okfn.org/site-admins/

The data from this sheet is loaded into a database. The admin page gives you actions to reload this data.

So:

1. Edit your config file (https://docs.google.com/spreadsheets/d/1FCAnp_sksyb2FREVjw-qpDbJEVo5efRqiQP1OT1krDM/edit#gid=0)
2. Reload config from your admin page
