### ISSUE TITLE
Application error on submitting first entry

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#598]
Attempted to add first entry on http://australia.census.okfn.org/census/submit/?dataset=budget&place=nt
<img width="892" alt="screenshot 2015-07-24 21 43 11" src="https://cloud.githubusercontent.com/assets/9379524/8873743/059e94fc-324d-11e5-8a45-b07898209009.png">

**Comment by pwalsh** [comment]
fixed.
