### ISSUE TITLE
Change +Add buttons to goto /Submit page and default Place and Dataset

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#599]
As discussed in #595, consider changing the behaviour of the **+Add** button in the grid display to take you to the /submit page and pre-fill the place and dataset values based on the location of the button in the grid.

So clicking **+Add** here...
<img width="247" alt="screenshot 2015-07-24 21 36 17" src="https://cloud.githubusercontent.com/assets/9379524/8873661/1cb7150c-324c-11e5-8e9f-3b13939b6e76.png">
Will take you to... (whoops #598)  /submit/?dataset=budget&place=nt

**Comment by pwalsh** [comment]
@morchickit what do you think. The only problem is (and maybe it is a big one) that the user does not get to see if there are already pending submissions.

**Comment by rgrp** [comment]
@pwalsh this will be resolved by planned major refactor of front page (at least, in part). Let's discuss.

**Comment by pwalsh** [comment]
Changes in #619 will cover this
