### ISSUE TITLE
Logged in, Press Submit Information, Asked to Login (again!)

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#600]
- From http://australia.census.okfn.org/place/nt and logged in
- Press Submit Information 
- Asked to Login again at http://id.census.okfn.org/login?next=census%2Fsubmit%2F%3Fdataset%3Dbudget%26place%3Dnt 

I shouldn't need to login again.
- is there a timeout?
- or is it because I have multiple google accounts (which I am prompted for which one to use when I do login again)?

<img width="578" alt="screenshot 2015-07-24 22 40 16" src="https://cloud.githubusercontent.com/assets/9379524/8874544/43f092ca-3255-11e5-9c88-30cc87cea67b.png">

**Comment by pwalsh** [comment]
A glitch in the Matrix :). This only happens when the server reloads, like if I deploy new code. Sorry for the inconvenience.
