### ISSUE TITLE
Grey out Submit information button when submission awaiting review

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#601]
When a dataset has a submission awaiting review, make it more obvious that you can't make another submission until the previous one is Approved/Rejected. (Grey out / disable button?)

<img width="1077" alt="screenshot 2015-07-24 22 54 45" src="https://cloud.githubusercontent.com/assets/9379524/8874750/0ecd37ae-3257-11e5-8cd7-5877012baacf.png">

**Comment by pwalsh** [comment]
Changes in #619 will cover this
