### ISSUE TITLE
Too easy to add submission by mistake

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#602]
When adding a submission for Noosa's Budget I tried to accept the suggested text for the Publisher's name by pressing Enter. This then: 
- defaulted values I hadn't enter to Not Sure
- didn't give me the choice to be Anonymous
- and added the submission

I think the problem was hitting Enter to select Noosa instead of clicking it with the mouse.
<img width="388" alt="screenshot 2015-07-26 12 08 28" src="https://cloud.githubusercontent.com/assets/9379524/8892185/25c25fc8-338f-11e5-9e99-964522b87f0a.png">

Not happy with the default action (which may have contributed to #594). Can the defaults be blank and require the user to explicitly answer and choose discloser?

@maxious feel free to reject or finish the [submission](http://au-city.census.okfn.org/census/submission/c9b0608d-79fa-4352-9a2f-aefb3599d4b5) using data at http://www.noosa.qld.gov.au/budget-2015-2016

**Comment by Stephen-Gates** [comment]
To test:
- that you can only add one submission at a time 
- and the risks of using the **+Add Information** button #595 

I tried to **+Add Information** over the top of the Noosa Budget submission above expecting to be stopped because one was waiting for review. Instead I was able to over-write the entry (so @maxious please review).

@pwalsh I think this is a bug.

**Comment by Stephen-Gates** [comment]
And I think my comment about no copyright statement on the web or within the PDF document was lost.

**Comment by pwalsh** [comment]
It is annoying behaviour, but this is how it has always been. I'm putting on the backlog for now.

**Comment by pwalsh** [comment]
Moved to #618
