### ISSUE TITLE
Comments missing in Census

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#603]
As discovered in #594 comments about the dataset are missing. Comments is the formatted text you enter in a submission here...
<img width="986" alt="screenshot 2015-07-26 19 51 14" src="https://cloud.githubusercontent.com/assets/9379524/8893335/0f262100-33d0-11e5-950e-ca15977e33db.png">

... and what gets displayed in the entry in the (i) icon here...
<img width="949" alt="screenshot 2015-07-26 19 51 45" src="https://cloud.githubusercontent.com/assets/9379524/8893338/29e301c0-33d0-11e5-881e-a05477b1a813.png">

**Comment by pwalsh** [comment]
fixed.
