### ISSUE TITLE
Comments not rendering Markdown

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#604]
You can use Markdown to format comments in your submission. These are not rendered correctly when the entry is displayed - e.g. hyperlinks below...

<img width="977" alt="screenshot 2015-07-26 20 31 30" src="https://cloud.githubusercontent.com/assets/9379524/8893501/8e64a6b2-33d5-11e5-93bc-2a8d4c34a396.png">

**Comment by pwalsh** [comment]
Moved into #618
