### ISSUE TITLE
Submission link does not work

### ISSUE THREAD

**Issue by schlos** [okfn/opendatacensus#606]
I just approved submission, it dissapeared from main screen, it's still visible in "changes" screen, but it says "rejected", and when I click on dataset link, I get error "There is no matching entry in our database. Please check the overview page for available entries.":
http://hr-city.census.okfn.org/changes/ --> http://hr-city.census.okfn.org/entry/ka/zoning

**Comment by pwalsh** [comment]
Hi @schlos I've fixed this issue, but I can't work out how to reproduce the fact that the record changed. Can you provide any more detail on the actions taken?

**Comment by pwalsh** [comment]
FIXED.

**Comment by schlos** [comment]
Thanks! I can confirm its working as expected.
