### ISSUE TITLE
Broken links to doc

### ISSUE THREAD

**Issue by davidegalletti** [okfn/opendatacensus#613]
on the [http://census.okfn.org/local/](http://census.okfn.org/local/)   page there are two broken links pointing at the [/doc](http://census.okfn.org/doc) page:
[Read the Overview of how censuses work in Census Administrator guide!](http://census.okfn.org/doc/#overview-of-how-a-census-is-structured)
[Basic configuration of the Census – see the instructions](http://census.okfn.org/doc/#configuring-your-census)

**Comment by pwalsh** [comment]
fixed.
