### ISSUE TITLE
Getting Admin access

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#614]
Hi, I'm the admin for the US City Open Data Census at http://us-city.census.okfn.org/

I am unable to login to the new version. Is there anything I need to do on my end?

My google email that should have access is andrewh@codeforamerica.org

**Comment by ondrae** [comment]
I want access so I can remove our Read Only warning banner and also refresh our list of place based reviewers.

**Comment by pwalsh** [comment]
Do you mean login, or, administer? You are not listed as an admin.

**Comment by ondrae** [comment]
Who is the admin listed? I'm the admin in practice. We coordinate with Sunlight Foundation as well.

**Comment by pwalsh** [comment]
I'll write to your email in the next hour.
