### ISSUE TITLE
Having trouble with submissions

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#616]
I've been doing some test submissions at http://us-city.census.okfn.org/place/williamsburg
They are all waiting for review before becoming visible. I thought the default was to auto-approve the first submission? I remember an [approve_first_submission](http://census.okfn.org/site-admins/#approvefirstsubmission) config variable, yet I'm not sure it works.

Also, it keeps telling me, the site admin, that I don't have permission to review. I've tried it with several different google accounts. Some should definitely have permissions.
![screen shot 2015-07-30 at 3 05 11 pm](https://cloud.githubusercontent.com/assets/595778/8992639/a98c4968-36cd-11e5-8cea-b2bd4566fbe8.png)

**Comment by pwalsh** [comment]
Hi @ondrae 

1. You can see that in the US City config, `approve_first_submission` is set to `FALSE`

2. See `reviewers` in your config file - are any of the email addresses you tried there? They should be if you have permissions to review, or, also check the places sheet.

**Comment by ondrae** [comment]
1. Setting that to TRUE works, thanks!
2. My admin email, which is in the reviewers field doesn't have permission. My personal gmail, which is in one of the place based reviewer fields, does work.

I don't need to have my Admin email working to promote the census though, so I'll get started.

Good work @pwalsh
