### ISSUE TITLE
Place view still only shows last years data

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#617]
#### Description
The place based views are still showing only the submissions for the last year, instead of summarizing all years of submissions.

#### Example
http://us-city.census.okfn.org/place/vegas is the same as http://us-city.census.okfn.org/place/vegas/2015 while http://us-city.census.okfn.org/place/vegas/2014 fills in the gaps.

**Comment by pwalsh** [comment]
That should be sorted now. Please confirm

**Comment by skorasaurus** [comment]
I had experienced the same bug a couple days ago with Cleveland; I can confirm that it's now fixed. Thanks @pwalsh

**Comment by pwalsh** [comment]
@skorasaurus thanks!
