### ISSUE TITLE
Enhancements to design + css

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#620]
@mintcanary will lead on this.

We want to bring the CSS forward from Bootstrap 2 to Bootstrap 3 or another framework, and work on other design enhancements, particularly on submission form and table views.

Also ref. last year's work on the [Global Index](http://index.okfn.org/), where we took the basics of the census site, and implemented on Bootstrap 3, with many enhancements to base color scheme and the display of data tables.

**Comment by pwalsh** [comment]
Moved from #619 as they it is really a design issue:

* [ ] Refactor the display of info to be more informative than coloured bars

**Comment by Stephen-Gates** [comment]
Really look forward to improvements here as the recent changes are not pretty. Can we consider making:
- the year badge more subtle, (grey text, no background)
- fitting in with the existing colour scheme (if you need to use colour)
- only show year badge, if the entry is from a prior year?
- on hover over entry, show tip for 9 answers and button to update (and thus remove the button)

<img width="984" alt="screenshot 2015-08-06 07 16 32" src="https://cloud.githubusercontent.com/assets/9379524/9098153/5c937bd4-3c0b-11e5-812e-280b0a4249e5.png">

**Comment by morchickit** [comment]
HI @Stephen-Gates - yes, we are aware this is not the most looking page (yet!).,
great feedback. @mintcanary is working on the new design, he will look at these comments. 

BTW - I am not a huge fan of tool tip, but Sam did take it into cosideration in the mock up.

**Comment by Stephen-Gates** [comment]
Thanks @morchickit - I'll be patient and look forward to a new design. Happy to leave it to the experts.

**Comment by pwalsh** [comment]
@morchickit can we close this issue now? As far as I see, this is done, and more specific UI/UX changes are treated in their own issues.

**Comment by mintcanary** [comment]
Just to note that the only work I've done is the table stuff. No attempt has been made to upgrade to Bootstrap 3 for example (this didn't seem a priority at this point).

**Comment by morchickit** [comment]
All depends on Sam. From my point of view, its good!

**Comment by mintcanary** [comment]
Sorry to pass the buck, but I think it depends on the current objectives and budget. There is loads that can be done to enhance the design. You could include the introduction of some branding in this. 

On the Bootstrap front, if we are concerned with visual design at this stage, then updating Bootstrap would be one useful step in a significant chunk of work. It's not clear whether there is the demand or budget to take this on at this point.

If we are not concerned with visual design at this stage (I think it's fine to say this is unashamedly a Bootstrap prototype), then I don't see any value in updating BS, and we should probably close this issue.

**Comment by pwalsh** [comment]
@morchickit and @mintcanary ok - just decide :).

**Comment by pwalsh** [comment]
FIXED.
