### ISSUE TITLE
Clent-side submission validation

### ISSUE THREAD

**Issue by vlevit** [okfn/opendatacensus#623]
# User story
Currently the error messages on submission form are very obscure. On error user has to retype all the information. It would be much better if user couldn't make wrong choices.

For server side validation see  #610.

**Comment by vlevit** [comment]
It's not finished yet but for the most part it should work.

The question order must be reviewed. It seems it doesn't follow [diagram flow] in every aspect. E.g. 'online' goes after 'free' on the diagram, and 'publisher' is just after 'exists' (is it right?)

[diagram flow]: https://docs.google.com/drawings/d/1jj0mnDjvzz-O8SNBgEhNTqsXa8SNdMoMeoxPoy-tBfE/

We do not handle expectFalse lists yet. It's only relevant for cases when the question is not in require list. Say if data is available digitally but is not public we should set 'online' to false and hide that question. Though currently can user can still select online.

Another issue is that zebra stripping doesn't work well if we hide questions. It seems there is no easy pure css solution, so we might end up implementing it in JS.

Asterisks on the required inputs must be brought back.

Probably we should submit form with Ajax, that wouldn't erase the form if it contains errors.

**Comment by vlevit** [comment]
The branch was merged to develop and deployed to the live site.

Currently we hide inapplicable questions only when a new entry gets submitted. If a user updates the existing submission or the submission is in a review mode we display all the questions (and only relevant dependants) but inapplicable questions are disabled. That is because @morchickit suggested that the reviewer must see all the questions.

Currently we reset answers for inapplicable questions and we do not restore them if user changes his answer back. This makes a poor user experience. I believe it shouldn't be hard to restore the previous answers.

**Comment by pwalsh** [comment]
Tasks:

* [ ] Fix bug where the `exists` dependants do not display when exists is yes, but they do display when `public is yes
* [ ] Reapply current dependant answer(s) instead of reset, if a parent answer was changed, and then changed back to original state

**Comment by pwalsh** [comment]
Hey @vlevit ! Can you please just give us a rundown on what tasks you think are remaining here, and we'll finish it off. Thanks!

**Comment by vlevit** [comment]
Hi Paul! Sorry that I've not updated the issue earlier. I just made the easy change to make `publisher` and `officialtitle` depend on `exists`. The patch is available here: http://vlevit.org/u/0001-Make-questions-publisher-and-officialtitle-depend-on.patch

As for the re-appliance of answers, unfortunately I've not found time to implement that.

As for `machinereadable` and `format` fields. I think we should make `format` depend on `exists` the same way as `machinereadable` depends on `exists`.

**Comment by pwalsh** [comment]
Thanks @vlevit 

I did those exists dependencies already, but thanks.

For the others, I'll leave it for now.

**Comment by pwalsh** [comment]
Will revert in https://github.com/okfn/opendatacensus/issues/693
