### ISSUE TITLE
Place and dataset validation

### ISSUE THREAD

**Issue by vlevit** [okfn/opendatacensus#625]
We should validate place and dataset values on form submission against database values.

Currently they are [validated only for not empty values](https://github.com/okfn/opendatacensus/blob/feature/validation/census/controllers/utils.js#L140-L141).

Since proper validation will likely involves DB queries probably validateData has to be converted to async function.

**Comment by pwalsh** [comment]
@brew assigning this as I think it can help you get into relevant parts of system

**Comment by brew** [comment]
Are we talking about here? https://github.com/okfn/opendatacensus/blob/b92eb50b68aa8538725591006c2cdef18af759e2/census/controllers/utils.js#L144

**Comment by pwalsh** [comment]
@brew looks like it.
