### ISSUE TITLE
Remove also on OKFN.ORG from the survey

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#627]
Hi,

This features is very confusing to submitters. They usually will not go and comment on other countries. Please remove it. 
![screen shot 2015-08-03 at 10 45 47](https://cloud.githubusercontent.com/assets/3273659/9035134/00575466-39cd-11e5-8cd2-a8467e0c7326.png)

**Comment by pwalsh** [comment]
As far I know, there is no way to remove this from disqus.

**Comment by pwalsh** [comment]
WONTFIX.
