### ISSUE TITLE
"Miami, FL" should technically be "Miami-Dade County, FL"

### ISSUE THREAD

**Issue by ErnieAtLYD** [okfn/opendatacensus#628]
I hate to say this, but technically **Miami, FL** should be **Miami-Dade County, FL.** When we started entering data we didn't know better. Technically the county has an unincorporated county service area which is not the same as the city of Miami's service areas.

**Comment by pwalsh** [comment]
Hi,

This is not a technical issue - it needs to be raised with the US City census administrators. Luckily, one of them is on here: cc @ondrae
