### ISSUE TITLE
Configure OK staging server for census

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#631]
On Heroku. 

*.next-census.okfn.org

See env vars for the production instance, and copy/modify for the staging instance.

**Comment by vlevit** [comment]
I set up the staging server. The database was imported from the production instance. We have reached the row limit of free plan though (12716/10000). We can either truncate the database or switch to Hobby Basic plan ($9/month).

I setup the Google app for staging server to make it possible to login and invite @rgrp and @pwalsh as owners of the app. I haven't tried registering the Facebook app. Probably we should also register a new Disqus account not to let it interfere with the production setup.

**Comment by rgrp** [comment]
I would suggest we truncate in some way if we can.

**Comment by vlevit** [comment]
Ok, we need to delete ~3000 rows.

Entry table has most of the entries: 8066. The Place table has 1874 rows.

If we count entries in each site we get the following numbers.

    SELECT site, COUNT(id) FROM entry GROUP BY site ORDER BY count DESC LIMIT 10;
      site   | count 
    ---------+-------
     global  |  3265
     us-city |  1312
     ro-city |   700
     gr-city |   370
     it-city |   343
     es-city |   283
     mx-city |   233
     tw-city |   205
     pt-city |   197
     gb-city |   179

It would be sufficient to drop all the global entries OR all of the entries from the folowing sites: us-city, ro-city, gr-city, it-city, es-city. We can also delete relevant places, though it would be only a few hundreds additionally.

I don't know if we need to import the database from the live site often to test some new features on the fresh data. If it is the case, we probably will need to truncate the database each time we do import.

**Comment by rgrp** [comment]
@vlevit as i said my sense is probably easier and more cost effective right now to pay heroku. We'll need to keep importing data across probably to try out migrations etc.

**Comment by vlevit** [comment]
@rgrp good, if it's okay I'll migrate the database to Hobby Basic ($9/month) plan tomorrow. (I have some work to be done today on the client site validation of submissions).

**Comment by vlevit** [comment]
Hmm, I see the first @rgrp comment in full only now. I have a page open and probably GitHub propagates only new comments but not updates.

It appeared that only the owner of the Heroku app can manage paid addon resources. And the only owner of the staging server is @pwalsh.

**Comment by pwalsh** [comment]
Tasks:

* [ ] Enable hobby plan for Heroku Postgres
* [ ] Copy a dump of current Production database to the staging server

**Comment by vlevit** [comment]
I think it's done.

**Comment by pwalsh** [comment]
FIXED.
