### ISSUE TITLE
Inconsistent behaviour on click of dataset needing review

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#639]
When I click an existing dataset entry that has a proposed change I see this:

<img width="485" alt="screenshot 2015-08-16 10 27 32" src="https://cloud.githubusercontent.com/assets/9379524/9291427/2148b5ea-4402-11e5-8983-5952a6ce6bac.png">

When I click a dataset that has been submitted for the first time, this screen flashed:

![fullsizerender](https://cloud.githubusercontent.com/assets/9379524/9291454/050fbb7e-4404-11e5-8a53-a9e57db66c4e.jpg)

Then I'm redirected to the review page. 
(A similar redirection occurs when I try to add a submission for the first time.)

It would make sense to me to have the first behaviour above apply to both types of submissions. Presenting a button that disappears before I can click it doesn't make sense to me.

**Comment by Stephen-Gates** [comment]
Behaviour seems slightly different between Safari (better) and Chrome

**Comment by pwalsh** [comment]
@mintcanary can you check this (I'm assuming you implemented it, LMK if not)?

**Comment by mintcanary** [comment]
Thanks for flagging this @Stephen-Gates and @pwalsh 

There are two options here:
 - Treat every cell the same, i.e remove direct action links
 - Avoid popup appearing when there is no data

I'm always keen to get user input where possible. @Stephen-Gates it sounds like you'd prefer the first of those two options. Is that correct?

**Comment by Stephen-Gates** [comment]
@mintcanary my expected behaviours:

- clicking an existing dataset with a revision shows a popup. 
Question - should the popup show the current or revised answers? (my leaning is current).
- clicking a new dataset with a submission waiting for review shows a popup - icons should show proposed answers, not `unsure` (we already know there's no data).
- clicking `+ Add` goes to straight to submit screen (via login). Popup does not add value here.

**Comment by mintcanary** [comment]
I think we need to be consistent with whether we show current or revised answers, so let's stick with current throughout for now. Maybe revised answers could be added (in addition), at a later stage.

I guess that makes the popup equally valueless in both scenarios, and we should disable the popup when there is no (current) data.

**Comment by Stephen-Gates** [comment]
Agree

**Comment by pwalsh** [comment]
looks like this was addressed in the above commit from sam
