### ISSUE TITLE
http://index.okfn.org/place/ question indicators are wrapping

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#640]
<img width="326" alt="screenshot 2015-08-16 14 16 47" src="https://cloud.githubusercontent.com/assets/9379524/9291958/a38b4b70-4421-11e5-94b2-dd9c3dc5a644.png">

**Comment by morchickit** [comment]
@mintcanary @pwalsh - this is for the next stage of the UX, not for the survey part. Will mark it for later.

**Comment by pwalsh** [comment]
@morchickit this belongs on the Index issue tracker, not here. Please move it and close this.

https://github.com/okfn/opendataindex/issues

**Comment by Stephen-Gates** [comment]
Sorry - my bad

**Comment by pwalsh** [comment]
moved to https://github.com/okfn/opendataindex/issues/98
