### ISSUE TITLE
Application error on submission view

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#643]
On the US City census, I can't view notifications. When I click on the comment button here, or any other notification:
![screen shot 2015-08-17 at 2 27 36 pm](https://cloud.githubusercontent.com/assets/595778/9316811/562401c6-44ec-11e5-9306-c74e1d6eba76.png)

I get an application error: 
http://us-city.census.okfn.org/census/submission/996b320b-7447-475e-86cb-663104e80a1c

**Comment by pwalsh** [comment]
FIXED.
