### ISSUE TITLE
Corrupted question dependants values in the DB

### ISSUE THREAD

**Issue by vlevit** [okfn/opendatacensus#644]
We have had the global index submission pages not working because of invalid dependant values in the DB. They looked as follows

           id        |        dependants         
    -----------------+---------------------------
     openlicense     | {licenseurl,i,c,e,n,s,e,u,r,l}
     machinereadable | {format,o,r,m,a,t}
     online          | {url,r,l}

etc. @morchickit reimported the questions but it didn't help. So I fixed them manually.

I'm still not familiar with DB loading mechanism. Though we'll probably need to test on staging to avoid data corruption on the production site.

Until the issue is fixed we should probably avoid importing questions to the database.

**Comment by vlevit** [comment]
The bug was that we were merging a comma-separated string containing dependants and the array of split dependants. Though we needed just to overwrite a string by the array.

I tested questions reload on staging, then pushed to the production and then tested on the production.

**Comment by vlevit** [comment]
I reloaded the questions for all the sites because most of them had contained the corrupted values.

**Comment by longhotsummer** [comment]
The develop branch still has this when reloading items that are arrays (eg. reviewers for datasets, dependants for questions, etc.)

**Comment by vlevit** [comment]
@longhotsummer Good catch! You are right, we have to fix those too: reviewers for both datasets and places. But dependants for questions should be fixed, right?

**Comment by longhotsummer** [comment]
Yes, dependants for questions is fixed, my bad.

**Comment by vlevit** [comment]
Reviewers for dataset and places should be fixed. Deployed to the production and reloaded.

It seems we don't have yet any reviewer for any dataset and we only have reviewers for US cities.

**Comment by pwalsh** [comment]
@vlevit correct: no dataset reviewers and only place reviewers in US cities.

**Comment by pwalsh** [comment]
FIXED.
