### ISSUE TITLE
{{Questions}} not processing Markdown

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#654]
Markdown is used in the questions for bold and dot points but is not displayed correctly 
in the {{Questions}} tag e.g. http://australia.census.okfn.org/faq#questions 

see questions: 

- Openly licensed?
- Is the data machine readable?
- Is the data provided on a timely and up to date basis?
- Publicly available?

Same issue exists when making a revision (and I assume a first submission)
![questionmd](https://cloud.githubusercontent.com/assets/9379524/9345988/5163da8e-465a-11e5-8a17-f1c6f3f3882e.PNG)

**Comment by morchickit** [comment]
Yes, I have noticed it too. @pwalsh  - I can't update the questions sheet since it's crashing the whole index when I am updating it. We need to look at it when you are back.

**Comment by morchickit** [comment]
@vlevit - I know we said we can upload it safely, but will it affect the markdown?

**Comment by vlevit** [comment]
@morchickit It's a totally different issue. I fixed the question loading bug (#644) so it shouldn't cause server errors. If markdown didn't work before it shouldn't start working now.

**Comment by morchickit** [comment]
@vlevit thanks!
Markdown used to work before. I don't know why its not working now...

**Comment by vlevit** [comment]
@morchickit My patch very unlikely could make markdown not working. Probably it's already not been working for some time. I'll have a look.

**Comment by vlevit** [comment]
@Stephen-Gates @morchickit I've pushed changes to the staging server:

http://australia.next-census.okfn.org/faq
http://global.next-census.okfn.org/census/submit/?place=au&dataset=timetables

Does it look good for you?

**Comment by Stephen-Gates** [comment]
@vlevit looks good to me - thanks - can close

**Comment by pwalsh** [comment]
@vlevit tasks to complete and close this issue:

* [ ] As discussed render markdown to HTML in loaders on explicit fields in config, questions, places, datasets
* [ ] Remove all related markdown filters from templates
* [ ] Deploy to staging, and reload all data for all censuses
* [ ] Deploy to production, and reload all data for all census

**Comment by pwalsh** [comment]
FIXED.
