### ISSUE TITLE
Add names of community coordinators to the Index survey main page

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#655]
As a user I want to know who is the coordinator in my area so I can ask them for guidance. 
@mintcanary - I think we should put this somewhere prominent in the page so people will know who to contact. In addition, we might also want to link to the forum home page. Currently the text that is in the homepage is from this excel - https://docs.google.com/spreadsheets/d/1BOsVfqSf3d1qitsrnqy500xkMawPxPtXBtKK7AIr4QI/edit#gid=0

**Comment by mintcanary** [comment]
Will these coordinators be providing their email addresses here?

Under what circumstances should users contact coordinators directly, rather than ask for guidance in the forum?

**Comment by morchickit** [comment]
Not everyone feel comfortable in the forum, so I guess this is for more 1 on 1 guidance of how to use the Index survey, and yes, I we will add their emails.

**Comment by mintcanary** [comment]
OK. I guess the most straight forward and flexible solution would be to just expand on the HTML that is already in that spreadsheet. Something like:

```html
<p>The Global Open Data Index is an initiative of <a href="http://okfn.org/">Open Knowledge</a> based on contributions from <a href="http://okfn.org/opendata/">open data</a> advocates and experts around the world.</p>
<p>For help with adding, changing or improving entries, we have the following resources:</p>
<div class="row">
    <div class="span4">
        <h3>Instructions</h3>
        <p>Read our instructions for contributing to the survey, and how you can make a difference in 5 easy steps.</p>
        <a href="/contribute/" class="btn btn-primary">Read Instructions</a>
    </div>
    <div class="span4">
        <h3>Support Forum</h3>
        <p>Conversations about operating, improving and contributing to the Global Open Data Index.</p>
        <a href="https://discuss.okfn.org/c/open-data-index" class="btn btn-primary">Go to Forum</a>
    </div>
    <div class="span4">
        <h3>Community Coordinators</h3>
        <p>Contact the coordinators directly.</p>
        <ul>
            <li><a href="mailto:x">Coordinator X</a></li>
            <li><a href="mailto:y">Coordinator Y</a></li>
        </ul>
    </div>
</div>
<hr>
```

**Comment by pwalsh** [comment]
@morchickit are we sure that all admins would want their email exposed to anyone who visits the census they administer? I think the forum is a more suitable place....

**Comment by morchickit** [comment]
sorry, I missed this. 
OK, can we add the forum to this?

**Comment by mintcanary** [comment]
There is already a link to the forum in the main navigation. One could be added to the body also, either  using my text above or your own.

**Comment by pwalsh** [comment]
closing.
