### ISSUE TITLE
Add Open Knowledge Favicon.ico and apple-touch-icon.png to all Census

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#659]
At present only the meta and global census have an Open Knowledge Favicon. 
<img width="596" alt="screenshot 2015-08-21 22 30 48" src="https://cloud.githubusercontent.com/assets/9379524/9408301/ea788f52-4854-11e5-9ea2-8c28f3013ad3.png">

I don't believe any census has an Apple-touch-icon.png [as used in the open data handbook](https://github.com/okfn/opendatahandbook/blob/gh-pages/apple-touch-icon.png) and [discussed here](https://discuss.okfn.org/t/dataportals-org-icon/954).

Please consider adding the open knowledge logo forms of these files for all census.

**Comment by Stephen-Gates** [comment]
You can find the FavIcons here https://drive.google.com/drive/folders/0ByBC-sFwdwtJR0I5QzJNdC1lcjA

**Comment by pwalsh** [comment]
Yes, we should fix this.

**Comment by pwalsh** [comment]
will be addressed in updated design. will be covered in new issues/tasks for that.
