### ISSUE TITLE
Review section still showing although I have no permission to review a dataset

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#660]
![screen shot 2015-08-21 at 16 08 35](https://cloud.githubusercontent.com/assets/3273659/9411633/02ea4232-481f-11e5-9a90-8d769d259619.png)

**Comment by pwalsh** [comment]
You do have permissions as you are a global reviewer

**Comment by morchickit** [comment]
Yes, and when I wanted to submit it gave me an error that I am not a
submitter. :-\

**Comment by pwalsh** [comment]
FIXED. bug was introduced yesterday in #647.
