### ISSUE TITLE
Broken icon link on dataset page

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#664]
On http://us-city.census.okfn.org/dataset/asset-disclosure the little icons for the comments about a dataset aren't working.
![screen shot 2015-08-24 at 10 56 22 am](https://cloud.githubusercontent.com/assets/595778/9447988/f567625c-4a4e-11e5-8ef1-adf9f027cc04.png)

I may be remembering wrong, but I though those had a popup that showed the comments the submitter had about their submission.

**Comment by pwalsh** [comment]
closing as the current ui will be replaced by something based on the Index UI ( http://index.okfn.org/dataset/statistics/ ) which has a different solution for this.
