### ISSUE TITLE
Datasets long description not showing

### ISSUE THREAD

**Issue by ondrae** [okfn/opendatacensus#665]
#### Description
We used to have a long detailed explanation of a dataset available on that datasets page. These are missing now, only the short description is showing.

For example in [this spreadsheet](https://docs.google.com/spreadsheets/d/1XYuDo5WLW4B-5Yi7gXiO_yxUTKYTizey07q3B0UV4Ko/edit#gid=2), we have a short description and a long description. Sunlight Foundation did a great job describing the datasets with lots of examples. We really want to show off those explanations again, as they'll help [prevent confusion](https://discuss.okfn.org/t/asset-disclosure-details/299?u=hackyourcity).

If I remember right, we had the short description showing everywhere, except for the dataset page at http://us-city.census.okfn.org/dataset/asset-disclosure and at a place like http://us-city.census.okfn.org/entry/sanfrancisco/asset-disclosure

#### Clues
* Here is the PR where I added the ability to use long descriptions https://github.com/okfn/opendatacensus/pull/356
* and here is where its got edited https://github.com/okfn/opendatacensus/pull/382
* yet on our us-city census, the long descriptions are showing up.

**Comment by ondrae** [comment]
I've tried using our long descriptions in the descriptions column. It bugged out
![screen shot 2015-08-25 at 2 24 09 pm](https://cloud.githubusercontent.com/assets/595778/9480003/1b59fd8a-4b35-11e5-9a3a-fddad0b609a2.png)

Does OKFN want to be able to use long descriptions again? If not, its okay. I can think of some ways for us to get around this. Like adding all those long descriptions to a table in the FAQ or something. We'll work it out.

**Comment by pwalsh** [comment]
@ondrae sure, I did not intentionally remove support. I've not seen long description before, and it is not documented ;). Your links to your original PRs help. I'll have a look but it will take a couple of days.

**Comment by pwalsh** [comment]
Also, we will be more than happy to accept PRs for this :). But if not, I'll get it done as soon as I can.

**Comment by morchickit** [comment]
Hold your horses - Paul, with all my love to the long descriptions, we have other local census issues to priorities before fixing it. @ondrae - in case you are not going to PR this, can you sync with sunlight and see if this is still needed and if there are any more requirements so we can look at all of them at once? @nealbastek - can you sync with @pwalsh and see what are the local index bugs and prioritise them with him?

**Comment by pwalsh** [comment]
Don;t worry @morchickit , the horses are in the stables ;)

**Comment by pwalsh** [comment]
As I never heard more on this, I'm closing as WONTFIX.
