### ISSUE TITLE
http://census.okfn.org/global/ should refer to Forum not Email list

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#667]
http://census.okfn.org/global/  states "Please add your suggestions to this Google Spreadsheet and **email the mailing list** with your suggestion so that people can discuss it."

Should refer to https://discuss.okfn.org/c/open-data-index instead

**Comment by pwalsh** [comment]
@morchickit was this fixed?

**Comment by morchickit** [comment]
Yes, you can close.
