### ISSUE TITLE
IE11 Wide screen formatting 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#668]
In IE11 when I resize the screen to wide I get this weird formatting. Note the duplicate columns.

Works fine in Chrome.

![widecensusie11](https://cloud.githubusercontent.com/assets/9379524/9460582/e9a5a60c-4b4a-11e5-8ff0-b6f7ee8ad096.PNG)

**Comment by jalbertbowden** [comment]
what version of windows?

**Comment by Stephen-Gates** [comment]
Windows 7 Enterprise Service Pack 1.
IE Version 11.0.9600.18059
