### ISSUE TITLE
Allow Support in top navigation to be configured to link to a Local Census Forum

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#671]
The new Support link in the top navigation bar links to https://discuss.okfn.org/c/open-data-index 

Consider allowing this to be configured in the [configuration file](http://census.okfn.org/site-admins/#general-config-options) so that a Census with a local forum (e.g. [Australia](https://discuss.okfn.org/c/open-data-index/australia-index), [USA](https://discuss.okfn.org/c/open-data-index/us-city-census)) can link directly to their local forum.

**Comment by pwalsh** [comment]
Thanks @Stephen-Gates it is a great idea, but going to the backlog for now until the Global submissions period is over.

**Comment by Stephen-Gates** [comment]
@pwalsh No problem - there's always plenty to do!

**Comment by pwalsh** [comment]
@brew i had the exact same request last week via email. This is pretty easy (just get the support link from the site settings sheet), and a nice small task to tackle and fix for the current codebase.
