### ISSUE TITLE
Error: format: You must not specify this field

### ISSUE THREAD

**Issue by gr33ndata** [okfn/opendatacensus#677]
While submitting the Transport Dataset for Tunisia, I got the following error (screenshot
![screen shot 2015-08-31 at 16 47 59](https://cloud.githubusercontent.com/assets/135069/9586196/9952e5a4-501b-11e5-94dd-244fbb62334c.png)
)

**Comment by pwalsh** [comment]
Hi there.

Could you please let me know the Y/N inputs you provided for the questions?

**Comment by gr33ndata** [comment]
I almost left last year's submission as it is, and added few more lines to the comment

**Comment by gr33ndata** [comment]
By the way, when this error is shown, the values in the text fields is duplicated, like, if a field has a url, "www.url.com" it end up being "www.url.comwww.url.com". Not sure how this note is useful.

**Comment by gr33ndata** [comment]
Got a similar error when submitting the budget for Tunisia. Seems like there is a problem with the Tunisian dataset or something. 

![screen shot 2015-09-01 at 17 00 55](https://cloud.githubusercontent.com/assets/135069/9607758/346e4948-50cb-11e5-9005-eca35416981b.png)

**Comment by pwalsh** [comment]
Hi @gr33ndata this should be fixed. Please confirm.

**Comment by gr33ndata** [comment]
It works now, thank you
