### ISSUE TITLE
Google deprecating web hosting from Drive

### ISSUE THREAD

**Issue by pwalsh** [okfn/opendatacensus#678]
http://googleappsupdates.blogspot.com/2015/08/deprecating-web-hosting-support-in.html

We use this as an "admin" interface for site administrators, and read the spreadsheets that admins edit in Google Drive, as CSV data via a url pattern available when the "public on the web" setting is activated.

This setting will be deprecated in August 2016.

Seeing as the app itself just needs a URL to a CSV file, I suggest an alternative may be a small CSV browser over CSV files hosted on GitHub. Such a tool is more widely useful too.

**Comment by longhotsummer** [comment]
I'm not convinced that they're deprecating exposing sheets as CSV. That's part of their Sheets API. I think they're disabling the ability to host google drive content as a static website.

**Comment by pwalsh** [comment]
@longhotsummer yes, I think you are right. I checked with some contacts I have too, and it seems that this change does not apply to our use of spreadsheets. Closing.
