### ISSUE TITLE
On overview page, hovering over a dateset doesn't show the + in Chrome like it does in Firefox

### ISSUE THREAD

**Issue by longhotsummer** [okfn/opendatacensus#683]
It shows it briefly, but once the page is loaded that functionality stops.

**Comment by pwalsh** [comment]
Hey @mintcanary are you able to have a quick look at this? If not LMK.

**Comment by mintcanary** [comment]
@pwalsh a quick look shows it working fine in my version of Chrome. @longhotsummer what version of Chrome are you using?

**Comment by longhotsummer** [comment]
Yup, this is fixed now both on census.okfn.org and after I caught up with develop. *shrug*
