### ISSUE TITLE
Scaling of census table breaks page header

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#687]
As I narrow the screen width, at some point the census table gets scaled to remain in full view on the page. This is great but it causes the icon the top right to drop out of place.

<img width="1184" alt="screenshot 2015-09-21 07 48 01" src="https://cloud.githubusercontent.com/assets/9379524/9983126/2927077c-6035-11e5-9893-b8b1883e8577.png">

**Comment by pwalsh** [comment]
wontfix in current codebase, but work this year will implement a new design.
