### ISSUE TITLE
Some Links in /Changes not working 

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#689]
On the [Changes page](http://australia.census.okfn.org/changes/) links to rejected or new submissions don't go to the submission so it can be (re)viewed but link back to the Changes page.

**Comment by longhotsummer** [comment]
Yeah, this sucks for scanning for new changes :(

:+1:

**Comment by borysyuk** [comment]
https://github.com/okfn/opendatacensus/pull/695
done.

**Comment by pwalsh** [comment]
FIXED.

**Comment by Stephen-Gates** [comment]
Awesome - thanks
