### ISSUE TITLE
Error in USA Government Spending 2014/15

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#691]
The USA had an [entry for Government Spending in 2014](https://twitter.com/AuOpenDataIndex/status/645281587291025408) now it is [gone](http://global.census.okfn.org/year/2014). The [2015 submission is approved](http://global.census.okfn.org/place/us/2015) and has a new submission on it - not sure if these two things are related.

**Comment by morchickit** [comment]
So, I Accepted the submission for 2015 and re-submitted again for the reviewer to look at it. @pwalsh can you check why it's gone on the data fro 2014?

**Comment by morchickit** [comment]
And thanks @stefanw for flagging this!

**Comment by pwalsh** [comment]
Hi all. I found the bug. No data is lost, don't worry. I'll push a fix soon.

**Comment by pwalsh** [comment]
FIXED in https://github.com/okfn/opendatacensus/commit/78564f7ca09ce94cca2a49062f6249576aadf304

and with the following SQL to fix data on 21 records across the whole instance (global and all local census instances):

```
UPDATE entry SET "isCurrent"=TRUE WHERE id IN ('8cfaac5c-4a16-43a1-b282-c27e34bd8e37', '63ba719b-7f98-48a0-9a25-4dc7b613f838', 'bdc52958-f763-472b-9331-5ab04c5edd2f', '2e284d49-7ec1-464d-8f07-9dc5735a744f', '6e7d2926-a169-4119-bef8-2d0775ebd7d3', '96369b42-f650-4f7f-b184-eb855b5724fc', 'b23b8a0d-edde-41ce-ad19-a1fa56593422', '03f07c1c-964b-41a9-896f-1b84d2afb712', '8e9e235e-d020-4333-8de0-3134e6a23c3f', 'b123693c-4c52-481d-91a6-76183cf69e05', '8bc3258f-f0e3-4dae-a081-4c03979b8739', 'bbf93f3f-71cf-45b7-9be6-b933b7597fe6', '8ca82925-8205-43e5-8acf-3832d8263687', 'ffd594d5-fdc8-4a52-9b82-f32cca436812', '4ae3ba17-1b3e-46e7-81ac-de4192289fee', '0393ba41-bfbe-490c-9ead-dde6a721fa3a', 'f0f99582-e89f-45ac-9371-a2c920c27028', 'ed7614b8-37c1-477d-bd9c-98ce5d300cb3', '44142aaf-66b4-4fcc-b127-8b74ea58cc4a', 'c716aeb9-44ec-4d5a-898f-0ee899cd227e', '8966de77-c677-46e1-9640-bf849d5c15e9', '63ba719b-7f98-48a0-9a25-4dc7b613f838', '8cfaac5c-4a16-43a1-b282-c27e34bd8e37');
```
