### ISSUE TITLE
Strengthen Survey Flow

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#699]
@morchickit as discussed.

In reviewing submissions there a number of time wasting submissions. I suggest the [survey flow](http://census.okfn.org/survey-flow/) be strengthen to require that comments be completed (to a minimum text length) when the answer to **Does the data exist?** is **No** or **Unsure**. 

The worst submission I have seen is answering **Yes** to **Does the data exist?** and **Unsure** to every other question, with **no comments** and from **Anonymous**. This is just lazy. It prevents others from making submissions and reviewers asking follow up questions.

**Comment by morchickit** [comment]
This is not relevant for this year's index, but for next year. We will have to review the methodology for it. WONT FIX for now (but will hopefully later)

**Comment by Stephen-Gates** [comment]
OK Thanks.
See also #688

**Comment by pwalsh** [comment]
Addressed by new methodology https://discuss.okfn.org/t/introducing-the-new-proposed-global-open-data-index-survey/3104
