### ISSUE TITLE
Sort Dataset page by Country

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#700]
It would be helpful for the review process if you could sort the dataset pages (e.g. http://global.census.okfn.org/dataset/weather/2015) by country name as well as current score.

**Comment by pwalsh** [comment]
@borysyuk this should be a very simple additional sort on the views for the dataset pages. If more complicated than that, just let me know here and we'll leave it in backlog.

**Comment by pwalsh** [comment]
DONE
