### ISSUE TITLE
Not able to submit new submission 

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#702]
Under Ireland Health Performance, this error occurred in the License questions 
![screen shot 2015-10-07 at 16 47 35](https://cloud.githubusercontent.com/assets/3273659/10342923/4eb7803a-6d13-11e5-9e54-fd6fc7964685.png)

**Comment by pwalsh** [comment]
@morchickit it is because machine readable is "Yes", yet format is blank. If machine readable is "Yes", we require a format.
