### ISSUE TITLE
Can't resubmit data

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#703]
http://global.census.okfn.org/submit/?place=tr&dataset=postcodes 
![screen shot 2015-10-11 at 15 27 39](https://cloud.githubusercontent.com/assets/3273659/10417249/b6c8c212-702c-11e5-80b6-a437dc0b7ab3.png)

Changed data from exist to not exist.

**Comment by pwalsh** [comment]
@morchickit this is a bad UX issue, but easily worked around (for now):

* change exists to "Yes"
* Clear the url and format fields (they shouldn't have values, but do I guess due to a bug in previous year's code)
* change exists back to "No"
* submit

**Comment by morchickit** [comment]
Oh boy... done.
