### ISSUE TITLE
Change message for reviewers 

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#705]
Need to change the text message here under the title "Important". @pwalsh - how do I do that? 
![screen shot 2015-10-12 at 23 26 25](https://cloud.githubusercontent.com/assets/3273659/10440606/b8edbf40-7138-11e5-80d7-3a9292aa28f1.png)

**Comment by pwalsh** [comment]
It is hard coded into the template. You could do a PR changing it directly (https://github.com/okfn/opendatacensus/blob/develop/census/views/_snippets/reviewer_actions.html), or, add the text here and we can do it.

**Comment by morchickit** [comment]
Done. Thanks.
