### ISSUE TITLE
Expose extra fields via API

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#706]
The message at the reviewer note suggest that the note would be displayed, but I can't see it anywhere on the census or the Index submissions. @pwalsh - where is it displayed?

**Comment by pwalsh** [comment]
Review notes are only (have only ever been) displayed on the actual submission page for an entry.

This page exists, but is not really accessible after a review has been accepted.

To see, you can:

* go to a submission
* take note of the URL (e.g.: `/submission/62baff7a-801c-4d55-a419-98bb58d46954`)
* accept the submission and write review notes
* go back to the submission URL
* see the review notes

**Comment by pwalsh** [comment]
@morchickit is there any action here? do you want them displayed anywhere else?

**Comment by morchickit** [comment]
Ideally, on the Index site, or at least in the raw data to download?

**Comment by pwalsh** [comment]
@roll (and cc @kravets-levko so he know you'll do this) some fields to add to all entries endpoints for API. You'll need them in the Index site so you can add them now as part of your work on the process.py script.

# Tasks

* [ ] reviewComments
* [ ] reviewed
* [ ] reviewResult
* [ ] isCurrent

The last three are boolean. As we use "Yes" and "No" for true/false in other places that we output such data, I suggest we use the same here for these fields.

https://github.com/okfn/opendatacensus/blob/develop/census/controllers/api.js#L204

**Comment by pwalsh** [comment]
DONE.
