### ISSUE TITLE
Simplify development environment setup.

### ISSUE THREAD

**Issue by gmccue** [okfn/opendatacensus#727]
I was considering lending some help with some of the open issues, but setting up a development environment seems unnecessarily tedious given the existence of tools like [Docker](https://www.docker.com/).
Would it be helpful to provide Docker integration?

**Comment by pwalsh** [comment]
Hi. I have a dockerfile started. I had build issues with node-gyp and simply did not get back to it. If I add my existing work to a new branch, would you like to continue on it?

**Comment by gmccue** [comment]
@pwalsh Yeah, that would be great!

**Comment by diraol** [comment]
+1 ! =)

**Comment by pwalsh** [comment]
Closing this now as @gmccue has started on it in #731
