### ISSUE TITLE
Questions do not reload in Spanish

### ISSUE THREAD

**Issue by morchickit** [okfn/opendatacensus#732]
https://docs.google.com/spreadsheets/d/1nwmk8uJEK-4K6-5SdBgoLUlUos-BhfYRgjS74YkhDGc/edit#gid=3

**Comment by pwalsh** [comment]
@morchickit can you please provide more info please, and for example, a particular census instance you are trying this on.

**Comment by morchickit** [comment]
@tlacoyodefrijol - I saw that this didn't work in the Mexican instance, right?

**Comment by pwalsh** [comment]
@morchickit with no steps to reproduce, I'm closing this.
