### ISSUE TITLE
Upgrading bootstrap and Mobile Responsive

### ISSUE THREAD

**Issue by diraol** [okfn/opendatacensus#733]
Hi!
I've upgraded twitter bootstrap version on the project (and some other JS libs), and I'm also improving the responsiveness of the project.
On my fork I've created a new branch for that.
How do you prefer to receive a Pull Request with my modifications? On the development branch or on a new branch? (I think that doing it on a new branch would be better, but I'm open to suggestions).

Cheers!

**Comment by pwalsh** [comment]
Hi @diraol that is awesome! New code should ideally come in a PR for the develop branch, from a branch named `feature/{name-of-feature}`, more or less following the [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/) conventions.

Thanks!

**Comment by pwalsh** [comment]
Hi @diraol how is this work going? I'd love to be able to get these changes into the main branch.

**Comment by pwalsh** [comment]
I'm closing this as we'll be refactoring the design and base on bootstrap 3 (or BS4)
