### ISSUE TITLE
IE11 Wide screen formatting (again)

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/opendatacensus#737]
Issue #668 seems to be back. I am using Windows 7 and Internet Explorer 11 and get this weird formatting. Works fine in Chrome.

Note the two "Total Score" headers...
![ie11error](https://cloud.githubusercontent.com/assets/9379524/12134634/e81ef1c6-b47c-11e5-98cd-61e6db7bc215.PNG)

When I reduce the screen width, the headers are fixed but note the OK logo spills over at the top of the page.
![ie11error2](https://cloud.githubusercontent.com/assets/9379524/12134704/96fb7e12-b47d-11e5-86d1-c6812547cac8.PNG)

**Comment by pwalsh** [comment]
@borysyuk can you please have a look at this

**Comment by borysyuk** [comment]
@pwalsh :
there are 2 problems: 
1. header logo doesn't look properly on some sites (like australia) under `body width < 1200px`, so i hide this logo when width less than 1200px
2. two "Total Score" headers... There are some problem with SexyTables. It doesn't refresh table headers when user resizes window

**Comment by pwalsh** [comment]
@borysyuk ok thanks. I've merged you changes for the header logo anyway.

**Comment by borysyuk** [comment]
@pwalsh : the error with "two "Total Score" headers.." has been reprodused on Chrome browser too.
It happens when you open page in small window then resize browser to maximum.

**Comment by pwalsh** [comment]
Closing as we will be implementing an updated design.
