### ISSUE TITLE
Sysadmin documentation - clarify how you reload stuff

### ISSUE THREAD

**Issue by rgrp** [okfn/opendatacensus#742]
I was trying to update a site admin and got a bit lost trying to work out how i would reload the overall config ...

Instructions say:

> Reload the Registry on your Census at http://{system_subdomain}.{base_domain}/control

But what is `http://{system_subdomain}.{base_domain}/control` for main census.okfn.org? deploy?

**Comment by brew** [comment]
@rgrp Can you point me to the instructions this refers to? I can't find the part you quoted.

**Comment by pwalsh** [comment]
@brew step-by-step section on http://census.okfn.org/sys-admins/

**Comment by pwalsh** [comment]
@brew I'm assigning this for current sprint.
