### ISSUE TITLE
New weighting

### ISSUE THREAD

**Issue by dannylammerhirt** [okfn/opendatacensus#759]
DESCRIPTION

This year's edition of GODI will introduce a new weighting (=score that each question adds to the total score of a dataset) for our questions. The weighting will have to take into account 1) new questions we inserted into the survey; 2) that we want to give some of our old questions more emphasis as well as 3) de-emphasize some other questions that had a too high score (such as the open licensing question). 

TASKS

- [x] Checking our criteria how to weight each question

- [x] Deciding with Katelyn which weigthing we want to present to forum

- [x] Post in forum - feedback open till 28 July

**Comment by morchickit** [comment]
@KateRogers can we close this? Anything to add here?

**Comment by dannylammerhirt** [comment]
Weighting finished and accessible at: https://docs.google.com/document/d/1jwK_UmWMkj1xz7LFhsttQQW34jJb1atr9AuJ_-vHk5M/edit
