### ISSUE TITLE
Scoping/Planning Internal Data Category Research 

### ISSUE THREAD

**Issue by KateRogers** [okfn/opendatacensus#769]
DESCRIPTION 
For data categories that are, in 2016, a lower priority or we have significant internal expertise, we will be conducting research in-house to better define the data categories and the relevant characteristics, to investigate use cases for the data categories, and map relevant stakeholders. We will publish this research when we launch the survey in October 2016 to help contributors understand the value of the data we are assessing.  

TASKS 
- [x] Develop project plan with OpenSpending Team (Victoria) for research on Budgets/Spending Categories 
- [x] Contract external research advisory (i.e. OpenData Services Cooperative) 
- [x] Preliminary Scoping for weather, national map, location, weather & legislation (potentially to be included with research done by the NDI). 
- [x] Finalise timelines for internal research

**Comment by morchickit** [comment]
@KateRogers are any of these done? What is the timeline for internal research (last checkbox) so I can plan @dannylammerhirt time for the month?

**Comment by KateRogers** [comment]
I am catching up with Danny (I planned a call for tomorrow, which was moved because you want to join for Thursday), I can let you know then @morchickit

**Comment by dannylammerhirt** [comment]
Research on datasets is finished and documented in this folder: https://drive.google.com/drive/folders/0B5j55T4ZyssBY0tKYUhFRUZQbzg.
