### ISSUE TITLE
Add dataset description and characteristics to entry form

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#789]
It's useful for submitters to have the dataset description and characteristics available on the entry page. It's available on the old design, but needs to be added to the new mockups: http://okfnlabs.org/census-mockup/form/

**Comment by smth** [comment]
Are "description" and "characteristics" two separate things? If so, what are "characteristics" here?

**Comment by brew** [comment]
Yes. The description is a paragraph or two of copy, and characteristics are a list of short phrases. Thanks for reminding me, we already have characteristics listed as options for a multiple choice question, so we only need the description now (which I think you've already accommodated).
