### ISSUE TITLE
Multi-choice widget should accommodate longer options

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#790]
The multichoice widget used to select dataset characteristics should be able to accommodate short phrases without breaking the layout, e.g.

* Scale of 1:250,000 (1 cm = 2.5km)	
* Markings of national roads	
* National borders	
* Marking of streams, rivers, lakes, mountains	
* Updated at least once a year

**Comment by smth** [comment]
@brew now by default these answers appear in a single column, which will avoid any issues created by long answers. The two column can be reintroduced by adding the `short` class [here](https://github.com/okfn/census-mockup/blob/master/templates/form.html#L643).

The nicest way of determining which layout is used would probably be to say that if the longest answer contains less than X characters, then add the `short` class. Failing that, being able to choose when creating the question should work.
