### ISSUE TITLE
Entry Review design for entry form

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#791]
The entry review tools are part of the entry form. They show some guidelines for review, the current value for each question, and provide tools for approving the entry with a reviewers comment. This functionality needs to be added to the new entry form design.

**Comment by smth** [comment]
I think this is all in now http://okfnlabs.org/census-mockup/form/

**Comment by brew** [comment]
@smth Would it be possible to have the Review/Submission instructions box outside of the `section > div.container` block that contains the main questions? These are controlled by React and I'd have to pass the instruction text into it from outside, which is a bit of pain.

**Comment by brew** [comment]
The review/submission instructions aren't hardcoded into the templates, they are rendered by nunjucks from template variables.

**Comment by smth** [comment]
Done. It's now in the same place as the other alert.

**Comment by brew** [comment]
- [x] No permission ribbon
- [ ] Pending status box
- [x] Review instructions
- [ ] Review comment box

**Comment by brew** [comment]
Closed by #820.
