### ISSUE TITLE
Current answers for each question in entry form

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#792]
If there is an existing current entry, the entry form should show the current values for each question in the entry form.

**Comment by smth** [comment]
Do old and new answer both need to be visible, or can the existing answer essentially look like a regular one, that has just been entered?

**Comment by brew** [comment]
The old and new answers need to be visible. This allows reviewers to see the current accepted value, and the value being proposed in the submission under review.

**Comment by smth** [comment]
OK, got it. So my next question would be, does this review need to take place within this entry form? Why not have a new page showing some kind of diff view, where you can accept / reject answers?

**Comment by brew** [comment]
I _think_ the previous version allowed reviewers to edit the submission before accepting. So, they'd need the answers to be in a form. It's convenient to reuse the existing entry form for this. Also, submitters themselves also see the current value in the current version as a guide for their submission.

**Comment by smth** [comment]
This is perhaps a discussion for the future. In the mean time I will create a space for existing answers.

Are we able to highlight (add a class to) specific questions that have changed / need reviewing?

**Comment by smth** [comment]
Done http://okfnlabs.org/census-mockup/form/

**Comment by brew** [comment]
@smth Don't close the issue please. I still need to implement it!
