### ISSUE TITLE
Add Dataset/Place dropdowns to top of entry form

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#793]
As previously discussed with @smth.

Each entry form captures data about a particular place/dataset combo. These act as the title for the entry form, providing context. I want these values to be editable, but not too editable (because they reload the page). They are currently dropdowns at the top form page:

<img width="880" alt="datasetplace" src="https://cloud.githubusercontent.com/assets/3993/18917953/22fa4012-8591-11e6-902f-9251eb8737d9.png">

However, changing the value of the dropdowns will reload the page with the appropriate questions for the dataset, and lose the any currently filled in data in the form as a side-effect.

I'd like for the Dataset and Place to be plaintext titles, that are somehow editable, but only after an explicit user action. e.g. They'd be plaintext titles that become useable dropdowns only when the users clicks an 'edit' link (or something else similar).

**Comment by smth** [comment]
As these reload the page, is there any reason they couldn't be anchor links, rather than selects?

**Comment by brew** [comment]
Actually, only the Dataset dropdown needs to reload the page. These two select fields don't actually contribute their data values to the main form on the page. The form below instead gets place and dataset values with additional hidden fields, prepopulated when the page loads. So, it would be possible these selects to be some other sort of non-form widget. How would it work with anchors?

**Comment by smth** [comment]
Thanks @brew Anchors were just as an example really, of an element that is not a `select`. `select`s being difficult to style. It seems to me that a drop-down much as you'd commonly see in site navigation would work equally well. My thinking here was basically that it would be crazy to use JS to replace the `selects` with other markup, if we could just use the other markup to begin with.

**Comment by smth** [comment]
So something like this @brew http://okfnlabs.org/census-mockup/form/

**Comment by brew** [comment]
I like that a lot. Would each item in the list be a link?

**Comment by smth** [comment]
Yeah, I think that makes the most sense.

**Comment by smth** [comment]
For consistency, I've added some JS to make this work on click. I think this is now done.
