### ISSUE TITLE
Error styling for the Entry form

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#812]
The new Entry form design needs error state for both the entire form, and for each specific field. The error field should be highlighted in someway and room for an error message detailing the problem.

**Comment by smth** [comment]
@brew I'd like to think (optimistically) that it was impossible to fill in the form incorrectly.
If we say that required fields are handled by not presenting a question until the previous one is filled. What potential error messages do we have for specific fields? I guess we need to check that URLs start with "http"?

**Comment by smth** [comment]
I've added an error message to one of the source fields [here](http://okfnlabs.org/census-mockup/form/). Let me know if we need anything else.

**Comment by brew** [comment]
We also need to be able to display form-wide errors at the top of the form. These may be a short heading followed by a list of one or more errors. Currently, if it uses the 'warning' styles it looks like this: 

<img width="1178" alt="screen shot 2016-10-31 at 14 26 15" src="https://cloud.githubusercontent.com/assets/3993/19857602/283b6606-9f76-11e6-98ee-8db8b7d37f8d.png">

Are you able to look at this @smth ?

**Comment by brew** [comment]
We also need general 'flash' messages. These can appear on any page. They currently look like this: 

<img width="1285" alt="screen shot 2016-10-31 at 14 54 56" src="https://cloud.githubusercontent.com/assets/3993/19858642/23e343fe-9f7a-11e6-96a1-5712c917f1fa.png">

**Comment by smth** [comment]
If they are errors you should probably replace `alert-warning` with `alert-danger` (these are default Bootstrap classes). I have added some styles to make the links and lists look a bit nicer.
