### ISSUE TITLE
NaN% in the Percentage open, at survey home

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#840]
_From @ppKrauss on November 26, 2016 10:10_

Hi, at http://global.survey.okfn.org/ a division by zero error in the top of the page.

_Copied from original issue: okfn/opendataindex#160_

**Comment by brew** [comment]
This only applies when no submission has yet been Published. Once a submission has been published, the scoring indicator works.

**Comment by ppKrauss** [comment]
Hi @brew, ok now the site is good (!). 

PS: for future versions... and a software engineering principle,   "when no submission has yet been" have non-zero and non-negligible time (was few days!)...  So need a litle `x? k/x: 0` code, is better than `k/x`.

**Comment by brew** [comment]
@ppKrauss My note above was mostly for myself, so I don't think it's fixed once there have been approved submissions :) I'm not closing this issue yet.
