### ISSUE TITLE
Add forum link to pending submission form

### ISSUE THREAD

**Issue by brew** [okfn/opendatacensus#848]
~~This applies only to GODI. Add a link to the GODI discussion forum to the pending submission forum, so issues with the submission can be raised and discussed. https://discuss.okfn.org/c/open-data-index/global-open-data-index-2016~~

Add a per-site config option to define a discussion forum url that will be displayed on pending submissions, so issues with the submission can be raised and discussed. Forum URLs hosted by the https://discuss.okfn.org/c/open-data-index Discourse instance will use the topic template to prepopulate the topic creation form with the appropriate dataset/place details and url back to the pending submission.

- [x] Confirm link wording with @tlacoyodefrijol
- [x] Confirm topic template wording with @tlacoyodefrijol 
- [ ] ~~Add `isGodi` flag to differentiate between Global and Local sites~~
- [x] Implement submission discussion forum link loading
- [x] Implement link in pending submission template

**Comment by Stephen-Gates** [comment]
Local forum could link to https://discuss.okfn.org/c/open-data-index/local-open-data-index

**Comment by morchickit** [comment]
I think that it should actually link to the specific local index category,
not the general one.

In any case, we need to have a different issue to the local ones.

**Comment by pwalsh** [comment]
I don't see why this is a global-only feature. Why not just add a submission discussion flag, in the form of a URL to a forum location? We could follow the discourse params convention to pre populate a new post with a title and a URL back to the submission in the body: https://meta.discourse.org/t/what-are-topic-templates/38295

**Comment by brew** [comment]
Thanks all - I'll adjust the issue above to allow a forum link to be specified on a per-site basis, and to prepopulate the discource topic appropriately if the forum link is the `discuss.okfn.org` url.
